/**
 * An inquiry against a lead: the door that forks one, the reads a member draws
 * it from, and the two walls that make a fork a thing that reads.
 *
 * TWO READS WIDEN TO THE PARENT AND THE WRITE DOES NOT. `read_session_store`
 * and `list_session_streams` answer the bearer's own session UNION the parent
 * of an `Inquiry`; `record_session_store_batch` is untouched and still writes
 * under `bound.session` alone. That asymmetry is the whole control, and a
 * migration that widened the third would end the slice's argument — so the two
 * are dropped and recreated here and the third is not named.
 *
 * THE STORE THE FORK WRITES IS REFUSED AND NOT SWEPT. A `BEFORE INSERT` trigger
 * raises for a session whose kind is `Inquiry`, so an inquiry's transcript is
 * never written and retention over it is not load-bearing. The pod discards its
 * own appends as well, and the pod is the thing being controlled, so the pod's
 * discard saves the wire and the trigger is the control. The answer a member
 * came for lives on the turn row, which is where it always was.
 *
 * THE PARENT IS READ TO A WHOLE TURN AND NOT TO ITS HEAD. A lead flushes
 * eagerly, so a lead mid-turn has batches standing that end inside an exchange,
 * and a fork resumed over those starts from a truncated assistant message. So
 * the parent read stops at `max(batch_last)` over the parent's settled turns,
 * and answers nothing where there is none. A session reading its OWN stream is
 * not bounded this way: its own batches are its own history and there is no
 * half-written exchange for it to resume over that it did not write.
 *
 * THE DOOR AND THE STORE AGREE BY SHARING ONE TEST. `LeadNotStarted` is exactly
 * the condition under which that ceiling is zero — no runtime reference, or no
 * settled turn that flushed a batch — so a lead the door lets a member fork is
 * a lead the store has something to answer with.
 *
 * `AlreadyOpen` IS TESTED BEFORE THE LEAD IS RESOLVED AT ALL. A retried `POST`
 * must answer the ordinal it already has, and a lead closed between the first
 * attempt and the retry would otherwise turn a fork that exists into
 * `LeadClosed` — telling a member their question was refused when it is already
 * queued. The pre-check matches on the principal and the turn, so a session
 * identity another principal minted falls through to the insert and RAISES
 * against 058's `agent_session_identity_is_never_reused` rather than being
 * answered.
 *
 * `open_lead_inquiry` TAKES NO ROSTER, NO ACCOUNT AND NO CREDENTIAL SLOT. The
 * API may open a session for the very principal that asked, which grants
 * nothing the caller does not already hold, and may not choose what that
 * session may do. The roster is this migration's own array literal generated
 * from `inquiryCapabilities`, and the slot, the account and the cluster are
 * COPIED FROM THE LEAD'S OWN ROW rather than drawn from the project's capacity
 * account: the fork reads the parent's store, the store's bytes sit on the
 * artifacts volume of the cluster the parent runs on, and a fork placed
 * elsewhere would resume nothing.
 *
 * THE OBJECTIVES ARE DERIVED FROM `inquirySystemPrompt` AND NOT RESPELLED. What
 * a fork is told beside the lead's own objectives is taken from that function
 * at build time, with a guard that it still appends; a prefix composed one way
 * in the interpreter and another in SQL is two prompts, and the pod would run
 * under whichever was written last.
 *
 * A GENERATED CHECK IS REPLACED WHERE IT WAS LAST WRITTEN.
 * `agent_session_prompt_is_bounded` was generated by 061 from
 * `sessionPromptCeilings`, and an inquiry's ceiling is the lead's plus what
 * being a fork means — so a fresh installation already holds the wide check and
 * one that ran 061 holds the narrow one for ever unless this replaces it. The
 * device is 059's, 061's and 062's and the reason has not changed.
 *
 * THE CLOSE IS A TRIGGER AND NOT A SWEEP. An inquiry whose one turn has ended
 * takes no other, and leaving it `Open` leaves a bearer that authenticates and
 * an idle pod the reaper has to find. It must NOT fire on `Claimed → Queued`:
 * an attempt lost mid-turn returns the turn to the mailbox, and closing there
 * would turn a lost pod into a lost answer. It fires for `kind='Inquiry'`
 * alone, because a lead's or a thread's turn ending is not the end of anything.
 *
 * A LISTING LEFT JOINS THE MEMBERSHIP, so an inquiry whose asker's membership
 * has been revoked is answered with no asker rather than hidden — 062's
 * argument for a thread's owner, for the same reason: a fork that ran under a
 * project's account is a fact its members are owed.
 */

import {
  agentSessionPromptCharsMax,
  inquiriesAnsweredMax,
  inquiriesOpenPerMemberMax,
  sessionStorePageBatchesMax,
  sessionStoreStreamsAnswered,
} from "../../../../contract/http.ts";
import {
  inquiryCapabilities,
  inquirySystemPrompt,
} from "../../../../interpreter/inquiry.ts";
import {
  apiRole,
  boundaryOwnerRole,
  inquiryCloseFunction,
  inquiryStoreRefusalFunction,
  leadInquiriesReadFunction,
  leadInquiryOpenFunction,
  leadInquiryReadFunction,
  schemaTextSet,
  sessionAttemptBindingFunction,
  sessionAttemptReadFunction,
  sessionStoreReadFunction,
  sessionStreamListFunction,
  sessionTurnEnqueueFunction,
  workerPlaneRole,
  type Migration,
} from "../shared.ts";

/** The states a turn is in when the exchange it names is whole. */
const settledTurnStates = "('Answered','Failed')";

/**
 * The last batch a session's SETTLED turns flushed, which is the head a fork
 * may resume from. It is ONE expression used by the store read's ceiling and by
 * the door's `LeadNotStarted`, so the two cannot come to disagree about what
 * there is to fork from; zero means there is no whole exchange to read.
 */
export function settledHead(partition: string, session: string): string {
  return `(SELECT coalesce(max(t.batch_last),0) FROM session_turn t
                WHERE ${partition} AND t.session=${session}
                  AND t.state IN ${settledTurnStates})`;
}

/** The states a turn is in when it will take no further attempt. */
const endedTurnStates = "('Answered','Failed','Abandoned')";

/** The roster an inquiry is opened with, rendered as the literal the definer writes. */
export const inquiryRosterLiteral = `ARRAY[${schemaTextSet([
  ...inquiryCapabilities,
])}]::text[]`;

/** A text no set of composed objectives contains, standing in for the lead's own. */
const leadPromptProbe = "the lead's own objectives";

/** The dollar-quoting tag the appended objectives are written under. */
const promptTag = "$inquiry_objectives$";

/**
 * What `inquirySystemPrompt` puts after the lead's own objectives, taken from
 * that function rather than written again here, and refused at build time if it
 * ever stops being an append or contains the tag it is quoted with.
 */
export const appendedObjectives = ((): string => {
  const composed = inquirySystemPrompt(leadPromptProbe);
  if (!composed.startsWith(leadPromptProbe))
    throw new Error(
      "migration 063: an inquiry's objectives no longer begin with the lead's own",
    );
  const appended = composed.slice(leadPromptProbe.length);
  if (appended.includes(promptTag))
    throw new Error(
      "migration 063: an inquiry's objectives contain the tag they are quoted with",
    );
  return `${promptTag}${appended}${promptTag}`;
})();

/**
 * The sessions one bearer may read a store of: its own, and its parent's — the
 * parent arm carrying the ceiling the read is bounded by and the own arm none,
 * so one join answers both and neither predicate is written twice. It needs no
 * kind test: 058's `agent_session_parent_is_whole` makes `parent_session`
 * non-null exactly for an `Inquiry`, so the parent join IS the kind, and that
 * constraint is where a kind later carrying a parent widens this.
 */
const readableSessions = `(
       SELECT k.session AS session,NULL::bigint AS ceiling
       UNION ALL
       SELECT s.parent_session,
              ${settledHead(
                "t.tenant=s.tenant AND t.project=s.project",
                "s.parent_session",
              )}
         FROM agent_session s
        WHERE s.tenant=k.tenant AND s.project=k.project AND s.session=k.session)`;

/**
 * The runtime reference a fork resumes from, which is its PARENT'S and never
 * its own — so an attempt following a lost one forks again from the lead rather
 * than resuming a fork whose store holds nothing. It needs no kind test for the
 * reason `readableSessions` gives: a session with no parent answers null here.
 */
const forkFrom = `(SELECT p.agent_reference FROM agent_session p
                WHERE p.tenant=s.tenant AND p.project=s.project
                  AND p.session=s.parent_session)`;

/**
 * The plane boundaries a fork changes, dropped and recreated because each is a
 * `RETURNS TABLE` function whose shape or whose session set moves — the same
 * device 059 and 061 use, with the grants re-issued rather than assumed to
 * survive.
 *
 * THE LISTING IS THE PARENT'S STREAMS WHOLE AND THE READ IS BOUNDED, because a
 * count here is whether a stream exists and not a length the resume trusts: the
 * pod asks each named stream for its batches and takes what the bounded read
 * answers, so a stream an unsettled turn alone wrote loads nothing rather than
 * loading half an exchange.
 */
const forkReads = [
  `DROP FUNCTION ${sessionAttemptReadFunction}(text)`,
  `CREATE FUNCTION ${sessionAttemptReadFunction}(in_secret_digest text)
     RETURNS TABLE(tenant text,project text,session text,attempt text,generation bigint,
                   kind text,principal text,capabilities text[],credential_slot text,
                   agent_reference text,system_prompt text,fork_from text,live boolean)
     LANGUAGE sql STABLE SECURITY DEFINER
     SET search_path=pg_catalog,public,pg_temp AS $$
       SELECT a.tenant,a.project,a.session,a.attempt,a.generation,s.kind,s.principal,
              s.capabilities,s.credential_slot,s.agent_reference,s.system_prompt,
              ${forkFrom},
              (a.state IN ('Placing','Running') AND s.state='Open'
               AND a.recovery_epoch=(SELECT epoch FROM recovery_epoch
                                      ORDER BY ordinal DESC LIMIT 1))
         FROM session_attempt a
         JOIN agent_session s ON s.tenant=a.tenant AND s.project=a.project
                             AND s.session=a.session
        WHERE a.bearer_secret_digest=in_secret_digest
     $$`,
  `DROP FUNCTION ${sessionStoreReadFunction}(text,bigint,text,bigint,bigint)`,
  `CREATE FUNCTION ${sessionStoreReadFunction}(
     in_secret_digest text,in_generation bigint,in_stream text,
     in_after bigint,in_limit bigint)
     RETURNS TABLE(batch bigint,digest text,bytes bigint)
     LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
       SELECT b.batch,b.digest,b.bytes
         FROM ${sessionAttemptBindingFunction}(in_secret_digest,in_generation) k
         CROSS JOIN LATERAL ${readableSessions} readable
         JOIN session_store_batch b ON b.tenant=k.tenant AND b.project=k.project
                                   AND b.session=readable.session
        WHERE b.stream=in_stream AND b.batch>coalesce(in_after,0)
          AND (readable.ceiling IS NULL OR b.batch<=readable.ceiling)
        ORDER BY b.batch
        LIMIT least(coalesce(in_limit,${sessionStorePageBatchesMax}),
                    ${sessionStorePageBatchesMax})
     $$`,
  `DROP FUNCTION ${sessionStreamListFunction}(text,bigint,bigint)`,
  `CREATE FUNCTION ${sessionStreamListFunction}(
     in_secret_digest text,in_generation bigint,in_max bigint)
     RETURNS TABLE(stream text,batches bigint)
     LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
       SELECT b.stream,count(*)::bigint
         FROM ${sessionAttemptBindingFunction}(in_secret_digest,in_generation) k
         CROSS JOIN LATERAL ${readableSessions} readable
         JOIN session_store_batch b ON b.tenant=k.tenant AND b.project=k.project
                                   AND b.session=readable.session
        GROUP BY b.stream ORDER BY b.stream
        LIMIT least(coalesce(in_max,${sessionStoreStreamsAnswered}),
                    ${sessionStoreStreamsAnswered})
     $$`,
];

/** The two walls the pod is not what enforces: nothing written, and nothing left open. */
const inquiryWalls = [
  `CREATE FUNCTION ${inquiryStoreRefusalFunction}() RETURNS trigger
     LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$
     BEGIN
       IF EXISTS(SELECT 1 FROM agent_session s
                  WHERE s.tenant=NEW.tenant AND s.project=NEW.project
                    AND s.session=NEW.session AND s.kind='Inquiry') THEN
         RAISE EXCEPTION
           'session % is an inquiry, and an inquiry answers aside rather than keeping a transcript',
           NEW.session USING ERRCODE = 'integrity_constraint_violation';
       END IF;
       RETURN NEW;
     END $$`,
  `ALTER FUNCTION ${inquiryStoreRefusalFunction}() OWNER TO ${boundaryOwnerRole}`,
  `REVOKE ALL ON FUNCTION ${inquiryStoreRefusalFunction}() FROM PUBLIC`,
  `CREATE TRIGGER session_store_batch_is_never_an_inquiry_s
     BEFORE INSERT ON session_store_batch
     FOR EACH ROW EXECUTE FUNCTION ${inquiryStoreRefusalFunction}()`,
  `CREATE FUNCTION ${inquiryCloseFunction}() RETURNS trigger
     LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$
     BEGIN
       UPDATE agent_session s SET state='Closed',closed_at=now()
        WHERE s.tenant=NEW.tenant AND s.project=NEW.project
          AND s.session=NEW.session AND s.kind='Inquiry';
       RETURN NULL;
     END $$`,
  `ALTER FUNCTION ${inquiryCloseFunction}() OWNER TO ${boundaryOwnerRole}`,
  `REVOKE ALL ON FUNCTION ${inquiryCloseFunction}() FROM PUBLIC`,
  `CREATE TRIGGER inquiry_closes_when_its_turn_ends
     AFTER UPDATE OF state ON session_turn
     FOR EACH ROW WHEN (NEW.state IN ${endedTurnStates})
     EXECUTE FUNCTION ${inquiryCloseFunction}()`,
];

/** The objectives column regenerated over the widened roster, as 061 renders it. */
const widenedPromptBound = [
  `ALTER TABLE agent_session
     DROP CONSTRAINT agent_session_prompt_is_bounded,
     ADD CONSTRAINT agent_session_prompt_is_bounded
     CHECK (system_prompt IS NULL
            OR length(system_prompt) BETWEEN 1 AND ${agentSessionPromptCharsMax})`,
];

/**
 * The one door a member asks through. It forks the project's lead under the
 * asker's own principal, writes the roster itself, and enqueues exactly one
 * turn — which is what makes one turn per inquiry a property of the mailbox
 * rather than of a runtime bound: nothing else in the tree enqueues a second.
 */
const askDoor = [
  `CREATE FUNCTION ${leadInquiryOpenFunction}(
     in_tenant text,in_project text,in_principal text,in_session text,
     in_turn text,in_question text)
     RETURNS TABLE(opened text,ordinal bigint,session text)
     LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
     DECLARE standing bigint; parent record; head bigint; held bigint; answered record;
     BEGIN
       SELECT t.ordinal INTO standing FROM session_turn t
         JOIN agent_session s ON s.tenant=t.tenant AND s.project=t.project
                             AND s.session=t.session
        WHERE s.tenant=in_tenant AND s.project=in_project AND s.session=in_session
          AND s.kind='Inquiry' AND s.principal=in_principal AND t.turn=in_turn;
       IF FOUND THEN
         RETURN QUERY SELECT 'AlreadyOpen'::text,standing,in_session; RETURN;
       END IF;
       SELECT s.session,s.state,s.agent_reference,s.credential_slot,
              s.account,s.cluster,s.system_prompt
         INTO parent FROM agent_session s
        WHERE s.tenant=in_tenant AND s.project=in_project AND s.kind='Lead'
        FOR UPDATE;
       IF NOT FOUND THEN
         RETURN QUERY SELECT 'NoLead'::text,NULL::bigint,NULL::text; RETURN;
       END IF;
       IF parent.state<>'Open' THEN
         RETURN QUERY SELECT 'LeadClosed'::text,NULL::bigint,parent.session; RETURN;
       END IF;
       SELECT ${settledHead(
         "t.tenant=in_tenant AND t.project=in_project",
         "parent.session",
       )} INTO head;
       IF parent.agent_reference IS NULL OR head=0 THEN
         RETURN QUERY SELECT 'LeadNotStarted'::text,NULL::bigint,parent.session;
         RETURN;
       END IF;
       SELECT count(*) INTO held FROM agent_session s
        WHERE s.tenant=in_tenant AND s.project=in_project
          AND s.kind='Inquiry' AND s.principal=in_principal AND s.state='Open';
       IF held>=${inquiriesOpenPerMemberMax} THEN
         RETURN QUERY SELECT 'InFlight'::text,NULL::bigint,NULL::text; RETURN;
       END IF;
       INSERT INTO agent_session
         (tenant,project,session,kind,principal,parent_session,capabilities,
          credential_slot,account,cluster,system_prompt)
       VALUES(in_tenant,in_project,in_session,'Inquiry',in_principal,parent.session,
              ${inquiryRosterLiteral},parent.credential_slot,parent.account,parent.cluster,
              parent.system_prompt || ${appendedObjectives});
       SELECT * INTO answered FROM ${sessionTurnEnqueueFunction}(
         in_tenant,in_project,in_session,in_turn,'Inquiry',in_question);
       RETURN QUERY SELECT 'Opened'::text,answered.ordinal,in_session;
     END $$`,
];

/**
 * What one inquiry answers with, which is the question, the answer and what the
 * turn cost. The question is the turn's INPUT DOCUMENT and this read hands it
 * over unparsed: the interpreter composes that document and the interpreter
 * reads it back, exactly as the plane stores a turn's input without reading it.
 */
const inquiryColumns = `session text,principal text,asker text,state text,
                   turn text,turn_state text,ordinal bigint,input text,result text,
                   failure text,asked_at timestamptz,model text,tokens bigint,
                   cost_micros bigint,duration_ms bigint,tools text[]`;

const inquirySelection = `SELECT s.session,s.principal,m.authority_subject,s.state,
              t.turn,t.state,t.ordinal,t.input,t.result,t.failure,t.enqueued_at,
              t.model,t.tokens,t.cost_micros,t.duration_ms,t.tools
         FROM agent_session s
         JOIN agent_session parent
           ON parent.tenant=s.tenant AND parent.project=s.project
          AND parent.session=s.parent_session AND parent.kind='Lead'
         JOIN session_turn t
           ON t.tenant=s.tenant AND t.project=s.project AND t.session=s.session
         LEFT JOIN project_membership m
           ON m.tenant=s.tenant AND m.project=s.project AND m.principal=s.principal
        WHERE s.tenant=in_tenant AND s.project=in_project`;

const inquiryReads = [
  `CREATE FUNCTION ${leadInquiriesReadFunction}(
     in_tenant text,in_project text,in_max bigint)
     RETURNS TABLE(${inquiryColumns})
     LANGUAGE sql STABLE SECURITY DEFINER
     SET search_path=pg_catalog,public,pg_temp AS $$
       ${inquirySelection}
        ORDER BY t.enqueued_at DESC,s.session DESC
        LIMIT least(coalesce(in_max,${inquiriesAnsweredMax}),${inquiriesAnsweredMax})
     $$`,
  `CREATE FUNCTION ${leadInquiryReadFunction}(
     in_tenant text,in_project text,in_session text)
     RETURNS TABLE(${inquiryColumns})
     LANGUAGE sql STABLE SECURITY DEFINER
     SET search_path=pg_catalog,public,pg_temp AS $$
       ${inquirySelection} AND s.session=in_session
     $$`,
];

/** Every door 063 declares, beside the argument types each is named by. */
const inquirySignatures: readonly (readonly [string, string, string])[] = [
  [sessionAttemptReadFunction, "text", workerPlaneRole],
  [sessionStoreReadFunction, "text,bigint,text,bigint,bigint", workerPlaneRole],
  [sessionStreamListFunction, "text,bigint,bigint", workerPlaneRole],
  [leadInquiryOpenFunction, "text,text,text,text,text,text", apiRole],
  [leadInquiriesReadFunction, "text,text,bigint", apiRole],
  [leadInquiryReadFunction, "text,text,text", apiRole],
];

const doorGrants = [
  ...inquirySignatures.map(
    ([name, signature]) =>
      `ALTER FUNCTION ${name}(${signature}) OWNER TO ${boundaryOwnerRole}`,
  ),
  ...inquirySignatures.map(
    ([name, signature]) =>
      `REVOKE ALL ON FUNCTION ${name}(${signature}) FROM PUBLIC`,
  ),
  ...inquirySignatures.map(
    ([name, signature, role]) =>
      `GRANT EXECUTE ON FUNCTION ${name}(${signature}) TO ${role}`,
  ),
];

/** Inquiries against a lead, forked and retained nowhere. */
export const migration063: Migration = {
  version: 63,
  name: "inquiries against a lead, forked and retained nowhere",
  statements: [
    ...forkReads,
    ...inquiryWalls,
    ...widenedPromptBound,
    ...askDoor,
    ...inquiryReads,
    ...doorGrants,
  ],
};
