export const baselineRelations: readonly string[] = [
  `CREATE TABLE public.admitted_worker (
    image text NOT NULL,
    name text NOT NULL,
    version text NOT NULL,
    published_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT admitted_worker_image_is_bounded CHECK (((length(image) >= 1) AND (length(image) <= 512))),
    CONSTRAINT admitted_worker_name_is_bounded CHECK (((length(name) >= 1) AND (length(name) <= 128))),
    CONSTRAINT admitted_worker_version_is_bounded CHECK (((length(version) >= 1) AND (length(version) <= 64)))
);`,
  `CREATE TABLE public.agent_session (
    tenant text NOT NULL,
    project text NOT NULL,
    session text NOT NULL,
    kind text NOT NULL,
    principal text NOT NULL,
    parent_session text,
    agent_reference text,
    capabilities text[] NOT NULL,
    credential_slot text NOT NULL,
    account text NOT NULL,
    cluster text NOT NULL,
    state text DEFAULT 'Open'::text NOT NULL,
    turn_next bigint DEFAULT 1 NOT NULL,
    attempt_next bigint DEFAULT 1 NOT NULL,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone,
    system_prompt text,
    opened_after_sequence bigint DEFAULT 0 NOT NULL,
    member_title text,
    hidden_at timestamp with time zone,
    CONSTRAINT agent_session_capabilities_are_known CHECK ((((cardinality(capabilities) >= 0) AND (cardinality(capabilities) <= 16)) AND (capabilities <@ ARRAY['RepositoryRead'::text, 'RepositoryWrite'::text, 'RunCommands'::text, 'ProjectRead'::text, 'DraftAuthor'::text, 'DraftOriginate'::text, 'LeadDecision'::text]))),
    CONSTRAINT agent_session_closing_is_whole CHECK (((state = 'Closed'::text) = (closed_at IS NOT NULL))),
    CONSTRAINT agent_session_counters_are_positive CHECK (((turn_next >= 1) AND (attempt_next >= 1))),
    CONSTRAINT agent_session_kind_is_known CHECK ((kind = ANY (ARRAY['Lead'::text, 'Thread'::text, 'Inquiry'::text]))),
    CONSTRAINT agent_session_member_title_is_bounded CHECK (((member_title IS NULL) OR ((length(member_title) >= 1) AND (length(member_title) <= 80)))),
    CONSTRAINT agent_session_opens_after_a_sequence CHECK ((opened_after_sequence >= 0)),
    CONSTRAINT agent_session_parent_is_whole CHECK (((kind = 'Inquiry'::text) = (parent_session IS NOT NULL))),
    CONSTRAINT agent_session_prompt_is_bounded CHECK (((system_prompt IS NULL) OR ((length(system_prompt) >= 1) AND (length(system_prompt) <= 136192)))),
    CONSTRAINT agent_session_state_is_known CHECK ((state = ANY (ARRAY['Open'::text, 'Closed'::text]))),
    CONSTRAINT agent_session_text_is_bounded CHECK ((((length(session) >= 1) AND (length(session) <= 256)) AND ((length(principal) >= 1) AND (length(principal) <= 256)) AND ((length(credential_slot) >= 1) AND (length(credential_slot) <= 256)) AND ((COALESCE(length(agent_reference), 1) >= 1) AND (COALESCE(length(agent_reference), 1) <= 256))))
);`,
  `CREATE TABLE public.capacity_account (
    account text NOT NULL,
    cluster text NOT NULL,
    reserved integer NOT NULL,
    maximum integer NOT NULL,
    policy_revision bigint NOT NULL,
    CONSTRAINT capacity_account_entitlement_is_ordered CHECK (((reserved >= 0) AND (maximum >= reserved))),
    CONSTRAINT capacity_account_identity_is_bounded CHECK (((length(account) >= 1) AND (length(account) <= 256))),
    CONSTRAINT capacity_account_policy_is_positive CHECK ((policy_revision >= 1))
);`,
  `CREATE TABLE public.commit_permit (
    tenant text NOT NULL,
    project text NOT NULL,
    permit text NOT NULL,
    attempt text NOT NULL,
    recovery_epoch text NOT NULL,
    lifecycle_generation bigint NOT NULL,
    state text DEFAULT 'Granted'::text NOT NULL,
    granted_at timestamp with time zone DEFAULT now() NOT NULL,
    concluded_at timestamp with time zone,
    CONSTRAINT commit_permit_conclusion_is_whole CHECK (((state = 'Concluded'::text) = (concluded_at IS NOT NULL))),
    CONSTRAINT commit_permit_generation_is_positive CHECK ((lifecycle_generation >= 1)),
    CONSTRAINT commit_permit_identity_is_bounded CHECK (((length(permit) >= 1) AND (length(permit) <= 256))),
    CONSTRAINT commit_permit_state_is_known CHECK ((state = ANY (ARRAY['Granted'::text, 'Concluded'::text])))
);`,
  `CREATE TABLE public.configuration_revision (
    tenant text NOT NULL,
    project text NOT NULL,
    revision text NOT NULL,
    parent text,
    canonical text NOT NULL,
    digest text NOT NULL,
    authority_kind text NOT NULL,
    authority_subject text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT configuration_revision_content_is_bounded CHECK (((length(canonical) >= 1) AND (length(canonical) <= 65536)))
);`,
  `CREATE TABLE public.decision_input (
    tenant text NOT NULL,
    project text NOT NULL,
    ordinal bigint NOT NULL,
    input_kind text NOT NULL,
    input_id text NOT NULL,
    base_priority text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    lifecycle_generation bigint NOT NULL,
    state text DEFAULT 'Pending'::text NOT NULL,
    decided_seq bigint,
    outcome_code text,
    refused_head bigint,
    refused_lifecycle_generation bigint,
    terminal_at timestamp with time zone,
    settled_authority_kind text,
    settled_authority_subject text,
    CONSTRAINT decision_input_kind_is_known CHECK ((input_kind = ANY (ARRAY['Operation'::text, 'Continuation'::text]))),
    CONSTRAINT decision_input_kind_state_agree CHECK ((((input_kind = 'Operation'::text) AND (state = ANY (ARRAY['Pending'::text, 'Journaled'::text, 'Answered'::text, 'Refused'::text, 'Cancelled'::text]))) OR ((input_kind = 'Continuation'::text) AND (state = ANY (ARRAY['Pending'::text, 'Journaled'::text, 'Stale'::text]))))),
    CONSTRAINT decision_input_ordinal_is_positive CHECK (((ordinal >= 1) AND (lifecycle_generation >= 1))),
    CONSTRAINT decision_input_outcome_is_whole CHECK ((((state = 'Journaled'::text) = (decided_seq IS NOT NULL)) AND ((state = 'Refused'::text) = (outcome_code IS NOT NULL)) AND ((state = 'Refused'::text) = (refused_head IS NOT NULL)) AND ((state = 'Refused'::text) = (refused_lifecycle_generation IS NOT NULL)) AND ((state = 'Pending'::text) = (terminal_at IS NULL)) AND ((settled_authority_kind IS NULL) = (settled_authority_subject IS NULL)) AND (COALESCE(decided_seq, (1)::bigint) >= 1))),
    CONSTRAINT decision_input_priority_is_known CHECK ((base_priority = ANY (ARRAY['Safety'::text, 'Completion'::text, 'Continuation'::text, 'Ordinary'::text]))),
    CONSTRAINT decision_input_state_is_known CHECK ((state = ANY (ARRAY['Pending'::text, 'Journaled'::text, 'Answered'::text, 'Refused'::text, 'Cancelled'::text, 'Stale'::text])))
);`,
  `CREATE TABLE public.deployment_authoring_policy (
    singleton boolean DEFAULT true NOT NULL,
    domain_configuration text NOT NULL,
    CONSTRAINT deployment_authoring_policy_domain_configuration_check CHECK (((length(domain_configuration) >= 1) AND (length(domain_configuration) <= 65536))),
    CONSTRAINT deployment_authoring_policy_singleton_check CHECK (singleton)
);`,
  `CREATE TABLE public.dispatch_candidate (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    ticket_version bigint NOT NULL,
    work_fanout bigint NOT NULL,
    program text NOT NULL,
    rework_policy text NOT NULL,
    finalization_pricing text NOT NULL,
    resume_pricing text NOT NULL,
    finalizer text NOT NULL,
    configuration_revision text NOT NULL,
    configuration_digest text NOT NULL,
    configuration_canonical text NOT NULL,
    CONSTRAINT dispatch_candidate_check CHECK (((ticket >= 1) AND (ticket_version >= 1) AND (work_fanout >= 1)))
);`,
  `CREATE TABLE public.dispatch_candidate_dependency (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    dependency bigint NOT NULL,
    CONSTRAINT dispatch_candidate_dependency_dependency_check CHECK ((dependency >= 1))
);`,
  `CREATE TABLE public.dispatch_view (
    tenant text NOT NULL,
    project text NOT NULL,
    recovery_epoch text NOT NULL,
    watermark bigint NOT NULL,
    schema_version integer NOT NULL,
    digest text NOT NULL,
    CONSTRAINT dispatch_view_check CHECK (((watermark >= 0) AND (schema_version = 1) AND (digest ~ '^[0-9a-f]{64}$'::text)))
);`,
  `CREATE TABLE public.draft (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    authoring_version bigint NOT NULL,
    state text NOT NULL,
    configuration_revision text NOT NULL,
    CONSTRAINT draft_state_is_known CHECK ((state = ANY (ARRAY['Draft'::text, 'Released'::text, 'Deleted'::text]))),
    CONSTRAINT draft_ticket_is_positive CHECK (((ticket >= 1) AND (authoring_version >= 1)))
);`,
  `CREATE TABLE public.draft_brief (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    intent text NOT NULL,
    branch text,
    finalization_mode text,
    finalization_target text,
    title text,
    repository text,
    CONSTRAINT draft_brief_branch_is_a_ref CHECK (((branch IS NULL) OR (((length(branch) >= 1) AND (length(branch) <= 256)) AND (branch ~~ 'refs/heads/%'::text) AND (branch !~ '[[:cntrl:]]'::text)))),
    CONSTRAINT draft_brief_finalization_is_whole CHECK (((finalization_mode <> ALL (ARRAY['PullRequest'::text, 'PullRequestMerge'::text])) OR ((branch IS NOT NULL) AND ((finalization_target IS NULL) OR (branch <> finalization_target))))),
    CONSTRAINT draft_brief_finalization_mode_is_known CHECK ((finalization_mode = ANY (ARRAY['Push'::text, 'PullRequest'::text, 'PullRequestMerge'::text]))),
    CONSTRAINT draft_brief_finalization_target_is_a_ref CHECK (((finalization_target IS NULL) OR (((length(finalization_target) >= 1) AND (length(finalization_target) <= 256)) AND (finalization_target ~~ 'refs/heads/%'::text) AND (finalization_target !~ '[[:cntrl:]]'::text)))),
    CONSTRAINT draft_brief_finalization_target_needs_a_mode CHECK (((finalization_target IS NULL) OR (finalization_mode IS NOT NULL))),
    CONSTRAINT draft_brief_intent_is_bounded CHECK (((length(intent) >= 1) AND (length(intent) <= 16384))),
    CONSTRAINT draft_brief_intent_renders CHECK ((translate(intent, chr(10), ' '::text) !~ '[[:cntrl:]]'::text)),
    CONSTRAINT draft_brief_title_is_a_bounded_line CHECK (((title IS NULL) OR (((length(title) >= 1) AND (length(title) <= 256)) AND (title !~ '[[:cntrl:]]'::text))))
);`,
  `CREATE TABLE public.draft_brief_check (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    ordinal integer NOT NULL,
    command text NOT NULL,
    CONSTRAINT draft_brief_check_is_a_bounded_command_line CHECK ((((length(command) >= 1) AND (length(command) <= 512)) AND (command !~ '[[:cntrl:]]'::text))),
    CONSTRAINT draft_brief_check_ordinal_is_bounded CHECK (((ordinal >= 1) AND (ordinal <= 8)))
);`,
  `CREATE TABLE public.draft_brief_link (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    ordinal integer NOT NULL,
    url text NOT NULL,
    CONSTRAINT draft_brief_link_is_a_bounded_https_url CHECK ((((length(url) >= 1) AND (length(url) <= 512)) AND (url ~~ 'https://%'::text) AND (url !~ '[[:cntrl:]]'::text))),
    CONSTRAINT draft_brief_link_ordinal_is_bounded CHECK (((ordinal >= 1) AND (ordinal <= 8)))
);`,
  `CREATE TABLE public.draft_revision (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    authoring_version bigint NOT NULL,
    configuration_revision text NOT NULL,
    authoring text NOT NULL,
    authority_kind text NOT NULL,
    authority_subject text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT draft_revision_content_is_bounded CHECK (((length(authoring) >= 1) AND (length(authoring) <= 65536)))
);`,
  `CREATE TABLE public.execution (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    ticket bigint NOT NULL,
    task bigint NOT NULL,
    source_request text NOT NULL,
    account text NOT NULL,
    cluster text NOT NULL,
    configuration_revision text NOT NULL,
    configuration_digest text NOT NULL,
    requirement_identity text NOT NULL,
    requirement_value jsonb NOT NULL,
    requirement_digest text NOT NULL,
    requirement_source text NOT NULL,
    platform_default_version bigint NOT NULL,
    status text DEFAULT 'Queued'::text NOT NULL,
    outcome text,
    blocked_reason text,
    result_manifest text,
    completion_operation text,
    attempt_next bigint DEFAULT 1 NOT NULL,
    retries_spent bigint DEFAULT 0 NOT NULL,
    placement_backoff_from timestamp with time zone,
    registered_at timestamp with time zone DEFAULT now() NOT NULL,
    terminal_at timestamp with time zone,
    CONSTRAINT execution_blocked_reason_is_known CHECK (((blocked_reason IS NULL) OR (blocked_reason = ANY (ARRAY['ExecutionPolicyDenied'::text, 'TicketConfigIncompatible'::text, 'ExecutionProfileUnavailable'::text, 'RuntimeVersionUnsupported'::text, 'RequiredCapabilityUnavailable'::text])))),
    CONSTRAINT execution_counters_are_positive CHECK (((ticket >= 1) AND (task >= 1) AND (attempt_next >= 1) AND (retries_spent >= 0))),
    CONSTRAINT execution_identity_is_bounded CHECK (((length(execution) >= 1) AND (length(execution) <= 256))),
    CONSTRAINT execution_outcome_is_known CHECK (((outcome IS NULL) OR (outcome = ANY (ARRAY['Passed'::text, 'Failed'::text, 'Blocked'::text])))),
    CONSTRAINT execution_outcome_is_whole CHECK ((((status = 'Terminal'::text) = (outcome IS NOT NULL)) AND ((status = 'Terminal'::text) = (completion_operation IS NOT NULL)) AND ((status = ANY (ARRAY['Terminal'::text, 'Cancelled'::text])) = (terminal_at IS NOT NULL)) AND (((outcome IS NOT NULL) AND (outcome IS DISTINCT FROM 'Blocked'::text)) = (result_manifest IS NOT NULL)) AND ((NOT (outcome IS DISTINCT FROM 'Blocked'::text)) = (blocked_reason IS NOT NULL)))),
    CONSTRAINT execution_platform_default_version_positive CHECK ((platform_default_version >= 1)),
    CONSTRAINT execution_requirement_source_known CHECK ((requirement_source = ANY (ARRAY['ExplicitTask'::text, 'TaskKindDefault'::text, 'TicketDefault'::text, 'PlatformDefault'::text]))),
    CONSTRAINT execution_status_is_known CHECK ((status = ANY (ARRAY['Queued'::text, 'Admitted'::text, 'Launching'::text, 'Running'::text, 'Terminal'::text, 'Cancelled'::text])))
);`,
  `CREATE TABLE public.execution_attempt (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    attempt_number bigint NOT NULL,
    generation bigint DEFAULT 1 NOT NULL,
    recovery_epoch text NOT NULL,
    state text DEFAULT 'Placing'::text NOT NULL,
    lease_owner text,
    lease_expires_at timestamp with time zone,
    workload text,
    evidence text,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    capability text NOT NULL,
    capability_secret_digest text NOT NULL,
    manifest text NOT NULL,
    cleanup_completed_at timestamp with time zone,
    CONSTRAINT execution_attempt_capability_digest_is_sha256 CHECK ((capability_secret_digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT execution_attempt_counters_are_positive CHECK (((attempt_number >= 1) AND (generation >= 1))),
    CONSTRAINT execution_attempt_ending_is_whole CHECK (((state = ANY (ARRAY['Placing'::text, 'Running'::text])) = (ended_at IS NULL))),
    CONSTRAINT execution_attempt_evidence_is_whole CHECK (((evidence IS NULL) OR (state <> ALL (ARRAY['Placing'::text, 'Running'::text])))),
    CONSTRAINT execution_attempt_lease_is_whole CHECK (((lease_owner IS NULL) = (lease_expires_at IS NULL))),
    CONSTRAINT execution_attempt_state_is_known CHECK ((state = ANY (ARRAY['Placing'::text, 'Running'::text, 'Reported'::text, 'Lost'::text, 'Withdrawn'::text, 'Superseded'::text]))),
    CONSTRAINT execution_attempt_text_is_bounded CHECK ((((length(attempt) >= 1) AND (length(attempt) <= 256)) AND ((COALESCE(length(lease_owner), 1) >= 1) AND (COALESCE(length(lease_owner), 1) <= 256)) AND ((COALESCE(length(workload), 1) >= 1) AND (COALESCE(length(workload), 1) <= 256)) AND (COALESCE(length(evidence), 0) <= 1024)))
);`,
  `CREATE TABLE public.execution_cluster (
    cluster text NOT NULL,
    slots_max integer NOT NULL,
    policy_revision bigint NOT NULL,
    CONSTRAINT execution_cluster_identity_is_bounded CHECK (((length(cluster) >= 1) AND (length(cluster) <= 256))),
    CONSTRAINT execution_cluster_policy_is_positive CHECK ((policy_revision >= 1)),
    CONSTRAINT execution_cluster_slots_are_bounded CHECK ((slots_max >= 0))
);`,
  `CREATE TABLE public.execution_request (
    tenant text NOT NULL,
    project text NOT NULL,
    request text NOT NULL,
    authorizing_seq bigint NOT NULL,
    effect_position integer NOT NULL,
    ticket bigint NOT NULL,
    ticket_version bigint NOT NULL,
    kind text NOT NULL,
    state text DEFAULT 'Open'::text NOT NULL,
    claim_owner text,
    claim_generation bigint DEFAULT 0 NOT NULL,
    claim_expires_at timestamp with time zone,
    capacity_account text,
    configuration_revision text,
    configuration_digest text,
    input_bundle text,
    input_bundle_digest text,
    CONSTRAINT execution_request_check CHECK (((claim_owner IS NULL) = (claim_expires_at IS NULL))),
    CONSTRAINT execution_request_check1 CHECK (((authorizing_seq >= 1) AND (effect_position >= 0) AND (ticket >= 1) AND (ticket_version = authorizing_seq) AND (claim_generation >= 0))),
    CONSTRAINT execution_request_kind_check CHECK ((kind = ANY (ARRAY['SpawnWork'::text, 'SpawnEvaluation'::text, 'CancelTicketWork'::text]))),
    CONSTRAINT execution_request_pins_are_whole CHECK ((((kind = ANY (ARRAY['SpawnWork'::text, 'SpawnEvaluation'::text])) = (capacity_account IS NOT NULL)) AND ((kind = ANY (ARRAY['SpawnWork'::text, 'SpawnEvaluation'::text])) = (configuration_revision IS NOT NULL)) AND ((kind = ANY (ARRAY['SpawnWork'::text, 'SpawnEvaluation'::text])) = (configuration_digest IS NOT NULL)) AND ((COALESCE(length(capacity_account), 1) >= 1) AND (COALESCE(length(capacity_account), 1) <= 256)))),
    CONSTRAINT execution_request_pins_its_bundle CHECK ((((kind = ANY (ARRAY['SpawnWork'::text, 'SpawnEvaluation'::text])) = (input_bundle IS NOT NULL)) AND ((input_bundle IS NULL) = (input_bundle_digest IS NULL)))),
    CONSTRAINT execution_request_state_check CHECK ((state = ANY (ARRAY['Open'::text, 'Registered'::text, 'Fulfilled'::text, 'Invalidated'::text])))
);`,
  `CREATE TABLE public.execution_request_task (
    tenant text NOT NULL,
    project text NOT NULL,
    request text NOT NULL,
    task bigint NOT NULL,
    kind text NOT NULL,
    stage bigint,
    CONSTRAINT execution_request_task_check CHECK ((((kind = 'Work'::text) AND (stage IS NULL)) OR ((kind = 'Evaluation'::text) AND (stage IS NOT NULL) AND (stage >= 0)))),
    CONSTRAINT execution_request_task_kind_check CHECK ((kind = ANY (ARRAY['Work'::text, 'Evaluation'::text]))),
    CONSTRAINT execution_request_task_task_check CHECK ((task >= 1))
);`,
  `CREATE TABLE public.execution_result (
    tenant text NOT NULL,
    project text NOT NULL,
    manifest text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    manifest_ordinal bigint NOT NULL,
    schema_version integer NOT NULL,
    digest text NOT NULL,
    verdict text NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT execution_result_counters_are_positive CHECK (((manifest_ordinal >= 1) AND (schema_version >= 1))),
    CONSTRAINT execution_result_digest_is_hex CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT execution_result_identity_is_bounded CHECK (((length(manifest) >= 1) AND (length(manifest) <= 256))),
    CONSTRAINT execution_result_verdict_is_known CHECK ((verdict = ANY (ARRAY['Pass'::text, 'Fail'::text])))
);`,
  `CREATE TABLE public.execution_result_artifact (
    tenant text NOT NULL,
    project text NOT NULL,
    manifest text NOT NULL,
    ordinal integer NOT NULL,
    role text NOT NULL,
    path text NOT NULL,
    digest text NOT NULL,
    bytes bigint NOT NULL,
    CONSTRAINT execution_result_artifact_count_is_bounded CHECK (((ordinal >= 1) AND (ordinal <= 256))),
    CONSTRAINT execution_result_artifact_digest_is_hex CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT execution_result_artifact_path_is_normalized CHECK ((((length(path) >= 1) AND (length(path) <= 256)) AND (path !~ '^/'::text) AND (path !~ '//'::text) AND (path !~ '[\\\\]'::text) AND (path !~ '(^|/)[.][.]?(/|$)'::text) AND (path !~ '[[:cntrl:]]'::text) AND (path !~ '(^|/)[[:space:]]'::text) AND (path !~ '[[:space:]](/|$)'::text))),
    CONSTRAINT execution_result_artifact_role_is_known CHECK ((role = ANY (ARRAY['Handoff'::text, 'Diagnostic'::text]))),
    CONSTRAINT execution_result_artifact_size_is_bounded CHECK (((bytes >= 0) AND (bytes <= 1073741824)))
);`,
  `CREATE TABLE public.execution_result_report (
    tenant text NOT NULL,
    project text NOT NULL,
    manifest text NOT NULL,
    report text NOT NULL,
    CONSTRAINT execution_result_report_report_check CHECK (((length(report) >= 1) AND (length(report) <= 8192))),
    CONSTRAINT execution_result_report_report_check1 CHECK ((report !~ '[[:cntrl:]]'::text))
);`,
  `CREATE TABLE public.execution_result_source (
    tenant text NOT NULL,
    project text NOT NULL,
    manifest text NOT NULL,
    repository text NOT NULL,
    ref text NOT NULL,
    commit text NOT NULL,
    base text NOT NULL,
    expected_base text NOT NULL,
    CONSTRAINT execution_result_source_base_check CHECK ((base ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)),
    CONSTRAINT execution_result_source_check CHECK ((base = expected_base)),
    CONSTRAINT execution_result_source_commit_check CHECK ((commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)),
    CONSTRAINT execution_result_source_expected_base_check CHECK ((expected_base ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)),
    CONSTRAINT execution_result_source_ref_check CHECK (((length(ref) >= 1) AND (length(ref) <= 256))),
    CONSTRAINT execution_result_source_repository_check CHECK (((length(repository) >= 1) AND (length(repository) <= 256)))
);`,
  `CREATE TABLE public.execution_run (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration_path text,
    configuration_digest text,
    configuration_bytes bigint,
    configuration_recorded_at timestamp with time zone,
    CONSTRAINT execution_run_configuration_is_bounded CHECK (((configuration_path IS NULL) OR (((length(configuration_path) >= 1) AND (length(configuration_path) <= 256)) AND (configuration_path !~ '^/'::text) AND (configuration_path !~ '//'::text) AND (configuration_path !~ '[\\\\]'::text) AND (configuration_path !~ '(^|/)[.][.]?(/|$)'::text) AND (configuration_path !~ '[[:cntrl:]]'::text) AND (configuration_path !~ '(^|/)[[:space:]]'::text) AND (configuration_path !~ '[[:space:]](/|$)'::text) AND (configuration_digest ~ '^[0-9a-f]{64}$'::text) AND ((configuration_bytes >= 0) AND (configuration_bytes <= 1048576))))),
    CONSTRAINT execution_run_configuration_is_whole CHECK ((((configuration_path IS NULL) = (configuration_digest IS NULL)) AND ((configuration_path IS NULL) = (configuration_bytes IS NULL)) AND ((configuration_path IS NULL) = (configuration_recorded_at IS NULL))))
);`,
  `CREATE TABLE public.execution_run_model_usage (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    model text NOT NULL,
    tokens_input bigint NOT NULL,
    tokens_output bigint NOT NULL,
    tokens_cache_creation bigint NOT NULL,
    tokens_cache_read bigint NOT NULL,
    cost_usd_micros bigint NOT NULL,
    CONSTRAINT execution_run_model_counts_are_bounded CHECK ((((tokens_input >= 0) AND (tokens_input <= '9007199254740991'::bigint)) AND ((tokens_output >= 0) AND (tokens_output <= '9007199254740991'::bigint)) AND ((tokens_cache_creation >= 0) AND (tokens_cache_creation <= '9007199254740991'::bigint)) AND ((tokens_cache_read >= 0) AND (tokens_cache_read <= '9007199254740991'::bigint)) AND ((cost_usd_micros >= 0) AND (cost_usd_micros <= '9007199254740991'::bigint)))),
    CONSTRAINT execution_run_model_is_bounded CHECK ((((length(model) >= 1) AND (length(model) <= 128)) AND (model !~ '[[:cntrl:]]'::text)))
);`,
  `CREATE TABLE public.execution_run_total (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    turns bigint NOT NULL,
    duration_ms bigint NOT NULL,
    duration_api_ms bigint NOT NULL,
    tokens_input bigint NOT NULL,
    tokens_output bigint NOT NULL,
    tokens_cache_creation bigint NOT NULL,
    tokens_cache_read bigint NOT NULL,
    cost_usd_micros bigint NOT NULL,
    cost_basis text NOT NULL,
    permission_denials bigint NOT NULL,
    result_subtype text,
    stop_reason text,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT execution_run_total_basis_is_known CHECK ((cost_basis = 'List'::text)),
    CONSTRAINT execution_run_total_counts_are_bounded CHECK ((((tokens_input >= 0) AND (tokens_input <= '9007199254740991'::bigint)) AND ((tokens_output >= 0) AND (tokens_output <= '9007199254740991'::bigint)) AND ((tokens_cache_creation >= 0) AND (tokens_cache_creation <= '9007199254740991'::bigint)) AND ((tokens_cache_read >= 0) AND (tokens_cache_read <= '9007199254740991'::bigint)) AND ((turns >= 0) AND (turns <= '9007199254740991'::bigint)) AND ((duration_ms >= 0) AND (duration_ms <= '9007199254740991'::bigint)) AND ((duration_api_ms >= 0) AND (duration_api_ms <= '9007199254740991'::bigint)) AND ((cost_usd_micros >= 0) AND (cost_usd_micros <= '9007199254740991'::bigint)) AND ((permission_denials >= 0) AND (permission_denials <= '9007199254740991'::bigint)))),
    CONSTRAINT execution_run_total_labels_are_bounded CHECK ((((result_subtype IS NULL) OR (((length(result_subtype) >= 1) AND (length(result_subtype) <= 64)) AND (result_subtype !~ '[[:cntrl:]]'::text))) AND ((stop_reason IS NULL) OR (((length(stop_reason) >= 1) AND (length(stop_reason) <= 64)) AND (stop_reason !~ '[[:cntrl:]]'::text)))))
);`,
  `CREATE TABLE public.execution_run_transcript_batch (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    batch bigint NOT NULL,
    path text NOT NULL,
    digest text NOT NULL,
    bytes bigint NOT NULL,
    events bigint NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT execution_run_batch_is_bounded CHECK ((((batch >= 1) AND (batch <= 4096)) AND ((bytes >= 0) AND (bytes <= 65536)) AND ((events >= 0) AND (events <= 65536)))),
    CONSTRAINT execution_run_batch_object_is_bounded CHECK ((((length(path) >= 1) AND (length(path) <= 256)) AND (path !~ '^/'::text) AND (path !~ '//'::text) AND (path !~ '[\\\\]'::text) AND (path !~ '(^|/)[.][.]?(/|$)'::text) AND (path !~ '[[:cntrl:]]'::text) AND (path !~ '(^|/)[[:space:]]'::text) AND (path !~ '[[:space:]](/|$)'::text) AND (digest ~ '^[0-9a-f]{64}$'::text)))
);`,
  `CREATE TABLE public.execution_run_turn (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    ordinal bigint NOT NULL,
    model text NOT NULL,
    tokens_input bigint NOT NULL,
    tokens_output bigint NOT NULL,
    tokens_cache_creation bigint NOT NULL,
    tokens_cache_read bigint NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT execution_run_turn_model_is_bounded CHECK ((((length(model) >= 1) AND (length(model) <= 128)) AND (model !~ '[[:cntrl:]]'::text))),
    CONSTRAINT execution_run_turn_ordinal_is_bounded CHECK (((ordinal >= 1) AND (ordinal <= 1000))),
    CONSTRAINT execution_run_turn_tokens_are_bounded CHECK ((((tokens_input >= 0) AND (tokens_input <= '9007199254740991'::bigint)) AND ((tokens_output >= 0) AND (tokens_output <= '9007199254740991'::bigint)) AND ((tokens_cache_creation >= 0) AND (tokens_cache_creation <= '9007199254740991'::bigint)) AND ((tokens_cache_read >= 0) AND (tokens_cache_read <= '9007199254740991'::bigint))))
);`,
  `CREATE TABLE public.finalization_attempt (
    tenant text NOT NULL,
    project text NOT NULL,
    attempt text NOT NULL,
    request text NOT NULL,
    ticket bigint NOT NULL,
    repository text NOT NULL,
    input_bundle text NOT NULL,
    input_bundle_digest text NOT NULL,
    target_ref text NOT NULL,
    target_commit text NOT NULL,
    strategy text NOT NULL,
    configuration_revision text NOT NULL,
    configuration_digest text NOT NULL,
    approval_required boolean NOT NULL,
    outcome text NOT NULL,
    candidate_commit text,
    failure_kind text,
    conflict_manifest text,
    conflict_manifest_digest text,
    attempt_digest text NOT NULL,
    prepared_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT finalization_attempt_commits_are_object_ids CHECK (((target_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text) AND ((candidate_commit IS NULL) OR (candidate_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)))),
    CONSTRAINT finalization_attempt_digest_is_hex CHECK (((attempt_digest ~ '^[0-9a-f]{64}$'::text) AND ((conflict_manifest_digest IS NULL) OR (conflict_manifest_digest ~ '^[0-9a-f]{64}$'::text)))),
    CONSTRAINT finalization_attempt_failure_kind_is_known CHECK (((failure_kind IS NULL) OR (failure_kind = ANY (ARRAY['MergeConflict'::text, 'PreparationFailed'::text])))),
    CONSTRAINT finalization_attempt_outcome_is_known CHECK ((outcome = ANY (ARRAY['Prepared'::text, 'Failed'::text]))),
    CONSTRAINT finalization_attempt_outcome_is_whole CHECK ((((outcome = 'Prepared'::text) = (candidate_commit IS NOT NULL)) AND ((outcome = 'Failed'::text) = (failure_kind IS NOT NULL)) AND ((conflict_manifest IS NULL) OR (failure_kind = 'MergeConflict'::text)) AND ((conflict_manifest IS NULL) = (conflict_manifest_digest IS NULL)))),
    CONSTRAINT finalization_attempt_strategy_is_known CHECK ((strategy = 'Merge'::text)),
    CONSTRAINT finalization_attempt_text_is_bounded CHECK ((((length(attempt) >= 1) AND (length(attempt) <= 256)) AND ((length(target_ref) >= 1) AND (length(target_ref) <= 256)) AND ((COALESCE(length(conflict_manifest), 1) >= 1) AND (COALESCE(length(conflict_manifest), 1) <= 256)))),
    CONSTRAINT finalization_attempt_ticket_is_positive CHECK ((ticket >= 1))
);`,
  `CREATE TABLE public.finalization_change_proposal (
    tenant text NOT NULL,
    project text NOT NULL,
    request text NOT NULL,
    permit text NOT NULL,
    proposal_request text NOT NULL,
    head_ref text NOT NULL,
    head_commit text NOT NULL,
    base_ref text NOT NULL,
    base_commit text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    creation text,
    creation_contradiction text,
    creation_evidence jsonb,
    reconciliation text,
    reconciliation_contradiction text,
    reconciliation_evidence jsonb,
    attempts integer DEFAULT 0 NOT NULL,
    refusals integer DEFAULT 0 NOT NULL,
    declines integer DEFAULT 0 NOT NULL,
    reconciliations integer DEFAULT 0 NOT NULL,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    merge text,
    merge_reason text,
    merge_commit text,
    merge_reading text,
    merge_reading_contradiction text,
    merge_reading_evidence jsonb,
    merge_attempts integer DEFAULT 0 NOT NULL,
    merge_refusals integer DEFAULT 0 NOT NULL,
    merge_declines integer DEFAULT 0 NOT NULL,
    merge_readings integer DEFAULT 0 NOT NULL,
    CONSTRAINT finalization_change_proposal_attempts_are_counted CHECK (((refusals >= 0) AND (declines >= 0) AND (reconciliations >= 0) AND ((attempts >= (refusals + declines)) AND (attempts <= ((refusals + declines) + 1))) AND ((creation IS NULL) OR (attempts = ((refusals + declines) + 1))))),
    CONSTRAINT finalization_change_proposal_commits_are_object_ids CHECK (((head_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text) AND (base_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text))),
    CONSTRAINT finalization_change_proposal_evidence_is_bounded CHECK ((((COALESCE(length((creation_evidence)::text), 1) >= 1) AND (COALESCE(length((creation_evidence)::text), 1) <= 131072)) AND ((COALESCE(length((reconciliation_evidence)::text), 1) >= 1) AND (COALESCE(length((reconciliation_evidence)::text), 1) <= 131072)))),
    CONSTRAINT finalization_change_proposal_identity_is_a_digest CHECK ((proposal_request ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT finalization_change_proposal_merge_is_whole CHECK ((((merge IS NULL) OR (merge = ANY (ARRAY['Merged'::text, 'HeadMoved'::text, 'NotMergeable'::text]))) AND ((merge_reason IS NULL) = (merge IS DISTINCT FROM 'NotMergeable'::text)) AND ((merge_reason IS NULL) OR (merge_reason = ANY (ARRAY['Conflict'::text, 'Blocked'::text]))) AND ((merge_commit IS NULL) = (merge IS DISTINCT FROM 'Merged'::text)) AND ((merge_commit IS NULL) OR (merge_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)) AND ((merge_reading IS NULL) OR (merge_reading = ANY (ARRAY['Accepted'::text, 'Unmerged'::text, 'Contradictory'::text, 'Absent'::text, 'Unstorable'::text]))) AND ((merge_reading_evidence IS NULL) OR (merge_reading IS NOT NULL)) AND ((merge_reading IS NULL) OR (merge_reading <> ALL (ARRAY['Accepted'::text, 'Unmerged'::text, 'Contradictory'::text])) OR (merge_reading_evidence IS NOT NULL)) AND ((merge_reading_contradiction IS NULL) = (merge_reading IS DISTINCT FROM 'Contradictory'::text)) AND ((merge_reading_contradiction IS NULL) OR (merge_reading_contradiction = ANY (ARRAY['Closed'::text, 'Merged'::text, 'Superseded'::text, 'ForgeMismatch'::text, 'RepositoryMismatch'::text, 'HeadMismatch'::text, 'BaseMismatch'::text, 'MetadataMismatch'::text, 'MarkerMismatch'::text]))) AND ((COALESCE(length((merge_reading_evidence)::text), 1) >= 1) AND (COALESCE(length((merge_reading_evidence)::text), 1) <= 131072)))),
    CONSTRAINT finalization_change_proposal_merges_are_counted CHECK (((merge_refusals >= 0) AND (merge_declines >= 0) AND (merge_readings >= 0) AND ((merge_attempts >= (merge_refusals + merge_declines)) AND (merge_attempts <= ((merge_refusals + merge_declines) + 1))) AND ((merge IS NULL) OR (merge_attempts = ((merge_refusals + merge_declines) + 1))) AND ((merge_attempts = 0) OR (creation_evidence IS NOT NULL) OR (reconciliation_evidence IS NOT NULL)))),
    CONSTRAINT finalization_change_proposal_results_are_whole CHECK ((((creation IS NULL) OR (creation = ANY (ARRAY['Created'::text, 'AlreadyExists'::text, 'Contradictory'::text, 'Unstorable'::text]))) AND ((reconciliation IS NULL) OR (reconciliation = ANY (ARRAY['Accepted'::text, 'Absent'::text, 'Contradictory'::text, 'Unstorable'::text]))) AND ((creation_evidence IS NULL) OR (creation IS NOT NULL)) AND ((reconciliation_evidence IS NULL) OR (reconciliation IS NOT NULL)) AND ((creation IS NULL) OR (creation <> ALL (ARRAY['Created'::text, 'AlreadyExists'::text, 'Contradictory'::text])) OR (creation_evidence IS NOT NULL)) AND ((reconciliation IS NULL) OR (reconciliation <> ALL (ARRAY['Accepted'::text, 'Contradictory'::text])) OR (reconciliation_evidence IS NOT NULL)) AND ((creation_contradiction IS NULL) = (creation IS DISTINCT FROM 'Contradictory'::text)) AND ((reconciliation_contradiction IS NULL) = (reconciliation IS DISTINCT FROM 'Contradictory'::text)) AND ((creation_contradiction IS NULL) OR (creation_contradiction = ANY (ARRAY['Closed'::text, 'Merged'::text, 'Superseded'::text, 'ForgeMismatch'::text, 'RepositoryMismatch'::text, 'HeadMismatch'::text, 'BaseMismatch'::text, 'MetadataMismatch'::text, 'MarkerMismatch'::text]))) AND ((reconciliation_contradiction IS NULL) OR (reconciliation_contradiction = ANY (ARRAY['Closed'::text, 'Merged'::text, 'Superseded'::text, 'ForgeMismatch'::text, 'RepositoryMismatch'::text, 'HeadMismatch'::text, 'BaseMismatch'::text, 'MetadataMismatch'::text, 'MarkerMismatch'::text]))))),
    CONSTRAINT finalization_change_proposal_text_is_bounded CHECK ((((length(permit) >= 1) AND (length(permit) <= 256)) AND ((length(head_ref) >= 1) AND (length(head_ref) <= 256)) AND ((length(base_ref) >= 1) AND (length(base_ref) <= 256)) AND ((length(title) >= 1) AND (length(title) <= 256)) AND ((length(body) >= 1) AND (length(body) <= 16384))))
);`,
  `CREATE TABLE public.finalization_reconciliation (
    tenant text NOT NULL,
    project text NOT NULL,
    permit text NOT NULL,
    candidate_commit text NOT NULL,
    target_ref text NOT NULL,
    verdict text NOT NULL,
    observed_commit text,
    reconciled_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT finalization_reconciliation_commits_are_object_ids CHECK (((candidate_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text) AND ((observed_commit IS NULL) OR (observed_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)))),
    CONSTRAINT finalization_reconciliation_reading_is_whole CHECK (((verdict = 'Unreadable'::text) = (observed_commit IS NULL))),
    CONSTRAINT finalization_reconciliation_ref_is_bounded CHECK (((length(target_ref) >= 1) AND (length(target_ref) <= 256))),
    CONSTRAINT finalization_reconciliation_verdict_is_known CHECK ((verdict = ANY (ARRAY['Promoted'::text, 'NotPromoted'::text, 'Unreadable'::text])))
);`,
  `CREATE TABLE public.finalization_request (
    tenant text NOT NULL,
    project text NOT NULL,
    request text NOT NULL,
    authorizing_seq bigint NOT NULL,
    effect_position integer NOT NULL,
    ticket bigint NOT NULL,
    ticket_version bigint NOT NULL,
    request_generation bigint NOT NULL,
    state text DEFAULT 'Open'::text NOT NULL,
    claim_owner text,
    claim_generation bigint DEFAULT 0 NOT NULL,
    claim_expires_at timestamp with time zone,
    recovery_epoch text,
    kind text NOT NULL,
    CONSTRAINT finalization_request_check CHECK (((claim_owner IS NULL) = (claim_expires_at IS NULL))),
    CONSTRAINT finalization_request_check1 CHECK (((authorizing_seq >= 1) AND (effect_position >= 0) AND (ticket >= 1) AND (ticket_version = authorizing_seq) AND (request_generation >= 1) AND (claim_generation >= 0))),
    CONSTRAINT finalization_request_claim_is_fenced CHECK ((((claim_owner IS NULL) = (recovery_epoch IS NULL)) AND ((COALESCE(length(claim_owner), 1) >= 1) AND (COALESCE(length(claim_owner), 1) <= 256)))),
    CONSTRAINT finalization_request_kind_is_known CHECK ((kind = ANY (ARRAY['RunFinalizer'::text, 'PromoteForHandoff'::text, 'PublishHandoff'::text]))),
    CONSTRAINT finalization_request_state_check CHECK ((state = ANY (ARRAY['Open'::text, 'Registered'::text, 'Fulfilled'::text, 'Invalidated'::text])))
);`,
  `CREATE TABLE public.finalization_request_configuration (
    tenant text NOT NULL,
    project text NOT NULL,
    request text NOT NULL,
    kind text NOT NULL,
    configuration_revision text CONSTRAINT finalization_request_configurat_configuration_revision_not_null NOT NULL,
    configuration_digest text CONSTRAINT finalization_request_configuratio_configuration_digest_not_null NOT NULL,
    repository text NOT NULL,
    target_ref text NOT NULL,
    credential_reference text CONSTRAINT finalization_request_configuratio_credential_reference_not_null NOT NULL,
    accepted_work_repository text,
    accepted_work_commit text,
    destination_path text,
    output text,
    request_digest text,
    CONSTRAINT finalization_request_configuration_commit_is_object_id CHECK (((accepted_work_commit IS NULL) OR (accepted_work_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text))),
    CONSTRAINT finalization_request_configuration_digest_is_hex CHECK (((configuration_digest ~ '^[0-9a-f]{64}$'::text) AND ((request_digest IS NULL) OR (request_digest ~ '^[0-9a-f]{64}$'::text)))),
    CONSTRAINT finalization_request_configuration_is_whole CHECK ((((kind = 'PublishHandoff'::text) = (accepted_work_repository IS NOT NULL)) AND ((kind = 'PublishHandoff'::text) = (accepted_work_commit IS NOT NULL)) AND ((kind = 'PublishHandoff'::text) = (destination_path IS NOT NULL)) AND ((kind = 'PublishHandoff'::text) = (output IS NOT NULL)) AND ((kind = 'PublishHandoff'::text) = (request_digest IS NOT NULL)))),
    CONSTRAINT finalization_request_configuration_kind_is_known CHECK ((kind = ANY (ARRAY['PromoteForHandoff'::text, 'PublishHandoff'::text]))),
    CONSTRAINT finalization_request_configuration_output_is_bounded CHECK (((output IS NULL) OR ((octet_length(output) >= 1) AND (octet_length(output) <= 262144)))),
    CONSTRAINT finalization_request_configuration_text_is_bounded CHECK ((((length(repository) >= 1) AND (length(repository) <= 256)) AND ((length(target_ref) >= 1) AND (length(target_ref) <= 256)) AND ((length(credential_reference) >= 1) AND (length(credential_reference) <= 256)) AND ((COALESCE(length(accepted_work_repository), 1) >= 1) AND (COALESCE(length(accepted_work_repository), 1) <= 256)) AND ((COALESCE(length(destination_path), 1) >= 1) AND (COALESCE(length(destination_path), 1) <= 512))))
);`,
  `CREATE TABLE public.forge_installation (
    forge text NOT NULL,
    app text NOT NULL,
    account text NOT NULL,
    account_kind text NOT NULL,
    installation_id text NOT NULL,
    tenant text NOT NULL,
    authority_kind text NOT NULL,
    authority_subject text NOT NULL,
    claimed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT forge_installation_account_kind_is_known CHECK ((account_kind = ANY (ARRAY['User'::text, 'Organization'::text]))),
    CONSTRAINT forge_installation_app_is_known CHECK ((app = ANY (ARRAY['portal'::text, 'worker'::text]))),
    CONSTRAINT forge_installation_is_bounded CHECK ((((length(forge) >= 1) AND (length(forge) <= 256)) AND ((length(account) >= 1) AND (length(account) <= 256)) AND ((length(installation_id) >= 1) AND (length(installation_id) <= 256)) AND ((length(tenant) >= 1) AND (length(tenant) <= 256)) AND ((length(authority_kind) >= 1) AND (length(authority_kind) <= 256)) AND ((length(authority_subject) >= 1) AND (length(authority_subject) <= 256))))
);`,
  `CREATE TABLE public.input_bundle (
    tenant text NOT NULL,
    project text NOT NULL,
    bundle text NOT NULL,
    digest text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT input_bundle_digest_is_hex CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT input_bundle_identity_is_bounded CHECK (((length(bundle) >= 1) AND (length(bundle) <= 256)))
);`,
  `CREATE TABLE public.input_bundle_reference (
    tenant text NOT NULL,
    project text NOT NULL,
    bundle text NOT NULL,
    ordinal integer NOT NULL,
    reference_kind text NOT NULL,
    reference_id text NOT NULL,
    reference_digest text,
    CONSTRAINT input_bundle_reference_count_is_bounded CHECK (((ordinal >= 1) AND (ordinal <= 1024))),
    CONSTRAINT input_bundle_reference_digest_is_hex CHECK (((reference_digest IS NULL) OR (reference_digest ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT input_bundle_reference_identity_is_bounded CHECK (((length(reference_id) >= 1) AND (length(reference_id) <= 256))),
    CONSTRAINT input_bundle_reference_kind_is_known CHECK ((reference_kind = ANY (ARRAY['ResultManifest'::text, 'ConfigurationRevision'::text, 'Repository'::text, 'FinalizationAttempt'::text, 'ConflictManifest'::text, 'TargetCommit'::text])))
);`,
  `CREATE TABLE public.installation_authority (
    singleton boolean DEFAULT true NOT NULL,
    installation_id text DEFAULT (gen_random_uuid())::text NOT NULL,
    established_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT installation_authority_id_is_canonical CHECK ((installation_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'::text)),
    CONSTRAINT installation_authority_singleton_check CHECK (singleton)
);`,
  `CREATE TABLE public.journal_entry (
    tenant text NOT NULL,
    project text NOT NULL,
    seq bigint NOT NULL,
    entry text NOT NULL,
    entry_digest text NOT NULL,
    prev_digest text NOT NULL,
    owner text NOT NULL,
    fencing_epoch bigint NOT NULL,
    recovery_epoch text NOT NULL,
    committed_at timestamp with time zone DEFAULT now() NOT NULL,
    cause_kind text NOT NULL,
    cause_id text NOT NULL,
    integrity_version integer DEFAULT 1 NOT NULL,
    configuration_revision text,
    configuration_digest text,
    event_schema_version integer DEFAULT 1 NOT NULL,
    decision_semantics_version integer DEFAULT 1 NOT NULL,
    CONSTRAINT journal_configuration_is_required_for_v2 CHECK (((integrity_version = 1) OR (configuration_revision IS NOT NULL))),
    CONSTRAINT journal_configuration_is_whole CHECK (((configuration_revision IS NULL) = (configuration_digest IS NULL))),
    CONSTRAINT journal_decision_semantics_version_is_positive CHECK ((decision_semantics_version >= 1)),
    CONSTRAINT journal_entry_seq_is_positive CHECK ((seq >= 1)),
    CONSTRAINT journal_event_schema_version_is_positive CHECK ((event_schema_version >= 1)),
    CONSTRAINT journal_integrity_version_is_known CHECK ((integrity_version = ANY (ARRAY[1, 2])))
);`,
  `CREATE TABLE public.native_action (
    tenant text NOT NULL,
    project text NOT NULL,
    action text NOT NULL,
    authorizing_seq bigint NOT NULL,
    effect_position integer NOT NULL,
    ticket bigint NOT NULL,
    action_version bigint NOT NULL,
    kind text NOT NULL,
    reason text NOT NULL,
    required_capability text NOT NULL,
    state text DEFAULT 'Open'::text NOT NULL,
    attempt text,
    resolution text,
    CONSTRAINT native_action_answer_is_whole CHECK (((state = 'Resolved'::text) = (resolution IS NOT NULL))),
    CONSTRAINT native_action_capability_is_known CHECK ((required_capability = ANY (ARRAY['ResolveTicket'::text, 'ApproveFinalization'::text]))),
    CONSTRAINT native_action_check CHECK (((authorizing_seq >= 1) AND (effect_position >= 0) AND (ticket >= 1) AND (action_version = authorizing_seq))),
    CONSTRAINT native_action_kind_is_known CHECK ((kind = ANY (ARRAY['TicketEscalation'::text, 'HandoffBlock'::text, 'FinalizationApproval'::text]))),
    CONSTRAINT native_action_kind_names_its_capability CHECK ((((kind = ANY (ARRAY['TicketEscalation'::text, 'HandoffBlock'::text])) = (required_capability = 'ResolveTicket'::text)) AND ((kind = 'FinalizationApproval'::text) = (required_capability = 'ApproveFinalization'::text)) AND ((kind = 'FinalizationApproval'::text) = (attempt IS NOT NULL)))),
    CONSTRAINT native_action_reason_check CHECK ((reason = ANY (ARRAY['NoReason'::text, 'WorkFailed'::text, 'ReworkBudgetExhausted'::text, 'FinalizationBudgetExhausted'::text, 'GasExhausted'::text, 'DependencyRevoked'::text, 'ExecutionPolicyDenied'::text, 'TicketConfigIncompatible'::text, 'ExecutionProfileUnavailable'::text, 'RuntimeVersionUnsupported'::text, 'RequiredCapabilityUnavailable'::text]))),
    CONSTRAINT native_action_state_check CHECK ((state = ANY (ARRAY['Open'::text, 'Resolved'::text, 'Withdrawn'::text])))
);`,
  `CREATE TABLE public.native_action_resolution (
    tenant text NOT NULL,
    project text NOT NULL,
    action text NOT NULL,
    resolution text NOT NULL,
    CONSTRAINT native_action_resolution_is_known CHECK ((resolution = ANY (ARRAY['Resume'::text, 'Revoke'::text, 'RetryHandoff'::text, 'AbandonHandoff'::text, 'Approve'::text, 'Decline'::text])))
);`,
  `CREATE TABLE public.operation (
    tenant text NOT NULL,
    project text NOT NULL,
    operation text NOT NULL,
    authority_kind text NOT NULL,
    authority_subject text NOT NULL,
    admission text NOT NULL,
    key_version text NOT NULL,
    key_digest text NOT NULL,
    payload_digest text NOT NULL,
    command text NOT NULL,
    accepted_at timestamp with time zone DEFAULT now() NOT NULL,
    command_tag text NOT NULL,
    via_session text,
    CONSTRAINT operation_admission_is_known CHECK ((admission = ANY (ARRAY['Ordinary'::text, 'CorrectnessReducing'::text])))
);`,
  `CREATE TABLE public.project (
    tenant text NOT NULL,
    project text NOT NULL,
    lifecycle text NOT NULL,
    lifecycle_generation bigint DEFAULT 1 NOT NULL,
    fencing_epoch bigint DEFAULT 1 NOT NULL,
    head bigint DEFAULT 0 NOT NULL,
    owner text,
    lease_expires_at timestamp with time zone,
    recovery_epoch text,
    ingress_next bigint DEFAULT 1 NOT NULL,
    ticket_next bigint DEFAULT 1 NOT NULL,
    notification_next bigint DEFAULT 1 NOT NULL,
    manifest_next bigint DEFAULT 1 NOT NULL,
    CONSTRAINT project_counters_are_positive CHECK (((lifecycle_generation >= 1) AND (fencing_epoch >= 1) AND (head >= 0))),
    CONSTRAINT project_ingress_is_positive CHECK ((ingress_next >= 1)),
    CONSTRAINT project_lifecycle_is_known CHECK ((lifecycle = ANY (ARRAY['Active'::text, 'Suspended'::text, 'IntegrityBlocked'::text, 'Deleting'::text, 'Retention'::text]))),
    CONSTRAINT project_manifest_next_is_positive CHECK ((manifest_next >= 1)),
    CONSTRAINT project_notification_next_is_positive CHECK ((notification_next >= 1)),
    CONSTRAINT project_ownership_is_whole CHECK ((((owner IS NULL) = (lease_expires_at IS NULL)) AND ((owner IS NULL) = (recovery_epoch IS NULL)))),
    CONSTRAINT project_ticket_next_is_positive CHECK ((ticket_next >= 1))
);`,
  `CREATE TABLE public.project_change (
    sequence bigint NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    kind text NOT NULL,
    resource text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    wake_reason text,
    CONSTRAINT project_change_kind_is_known CHECK ((kind = ANY (ARRAY['Operation'::text, 'Ticket'::text, 'Draft'::text, 'Configuration'::text, 'Project'::text, 'Execution'::text, 'NativeAction'::text, 'AgenticRefusal'::text, 'Session'::text]))),
    CONSTRAINT project_change_resource_is_bounded CHECK (((length(resource) >= 1) AND (length(resource) <= 3225))),
    CONSTRAINT project_change_wake_reason_is_known CHECK (((wake_reason IS NULL) OR (wake_reason = ANY (ARRAY['TicketRefused'::text, 'RefusalLifted'::text, 'DraftDeleted'::text, 'TicketEscalated'::text, 'TicketCompleted'::text, 'TicketAbandoned'::text]))))
);`,
  `CREATE TABLE public.project_continuation (
    tenant text NOT NULL,
    project text NOT NULL,
    continuation text NOT NULL,
    kind text NOT NULL,
    authorizing_seq bigint NOT NULL,
    effect_position integer NOT NULL,
    ticket bigint NOT NULL,
    expected_ticket_version bigint NOT NULL,
    expected_phase text NOT NULL,
    task_set_generation bigint NOT NULL,
    CONSTRAINT project_continuation_check CHECK (((authorizing_seq >= 1) AND (effect_position >= 0) AND (ticket >= 1) AND (expected_ticket_version >= 1) AND (task_set_generation >= 1))),
    CONSTRAINT project_continuation_expected_phase_check CHECK ((expected_phase = ANY (ARRAY['Pending'::text, 'Working'::text, 'Evaluating'::text, 'Finalizing'::text, 'PublishingHandoff'::text, 'HandoffBlocked'::text, 'Done'::text, 'Abandoned'::text, 'Escalated'::text, 'Revoked'::text]))),
    CONSTRAINT project_continuation_kind_check CHECK ((kind = ANY (ARRAY['ReduceWork'::text, 'ReduceEvaluation'::text])))
);`,
  `CREATE TABLE public.project_notification (
    tenant text NOT NULL,
    project text NOT NULL,
    ordinal bigint NOT NULL,
    kind text NOT NULL,
    resource text NOT NULL,
    project_seq bigint,
    authoring_version bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT project_notification_kind_is_known CHECK ((kind = ANY (ARRAY['Operation'::text, 'Ticket'::text, 'Draft'::text, 'Configuration'::text, 'Project'::text]))),
    CONSTRAINT project_notification_values_are_bounded CHECK (((ordinal >= 1) AND ((length(resource) >= 1) AND (length(resource) <= 256)) AND (COALESCE(project_seq, (1)::bigint) >= 1) AND (COALESCE(authoring_version, (1)::bigint) >= 1)))
);`,
  `CREATE TABLE public.project_readiness (
    tenant text NOT NULL,
    project text NOT NULL,
    ready boolean NOT NULL,
    generation bigint NOT NULL,
    CONSTRAINT project_readiness_generation_is_positive CHECK ((generation >= 1))
);`,
  `CREATE TABLE public.project_repository (
    tenant text NOT NULL,
    project text NOT NULL,
    repository text NOT NULL,
    recovery_epoch text NOT NULL,
    bound_at timestamp with time zone DEFAULT now() NOT NULL,
    landing_mode text DEFAULT 'Push'::text NOT NULL,
    retired_at timestamp with time zone,
    CONSTRAINT project_repository_identity_is_bounded CHECK (((length(repository) >= 1) AND (length(repository) <= 256))),
    CONSTRAINT project_repository_landing_mode_is_known CHECK ((landing_mode = ANY (ARRAY['Push'::text, 'PullRequest'::text, 'PullRequestMerge'::text])))
);`,
  `CREATE TABLE public.project_repository_bind_operation (
    operation text NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    repository text NOT NULL,
    recovery_epoch text NOT NULL,
    authority_kind text NOT NULL,
    authority_subject text NOT NULL,
    outcome text NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT project_repository_bind_operation_is_bounded CHECK ((((length(operation) >= 1) AND (length(operation) <= 256)) AND ((length(repository) >= 1) AND (length(repository) <= 256)) AND ((length(authority_kind) >= 1) AND (length(authority_kind) <= 256)) AND ((length(authority_subject) >= 1) AND (length(authority_subject) <= 256)))),
    CONSTRAINT project_repository_bind_operation_was_accepted CHECK ((outcome = ANY (ARRAY['Bound'::text, 'AlreadyBound'::text])))
);`,
  `CREATE TABLE public.recovery_epoch (
    ordinal bigint NOT NULL,
    epoch text NOT NULL,
    established_at timestamp with time zone DEFAULT now() NOT NULL
);`,
  `CREATE TABLE public.repository_configuration_provenance (
    tenant text NOT NULL,
    project text NOT NULL,
    revision text NOT NULL,
    digest text NOT NULL,
    repository text NOT NULL,
    repository_commit text NOT NULL,
    path text NOT NULL,
    name text NOT NULL,
    CONSTRAINT repository_configuration_commit_is_git_object CHECK ((repository_commit ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'::text)),
    CONSTRAINT repository_configuration_digest_is_sha256 CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT repository_configuration_name_is_bounded CHECK ((((length(name) >= 1) AND (length(name) <= 128)) AND (name ~ '^[A-Za-z0-9]([A-Za-z0-9._-]*[A-Za-z0-9])?$'::text))),
    CONSTRAINT repository_configuration_path_is_bounded CHECK ((((length(path) >= 1) AND (length(path) <= 256)) AND (path ~ '^\\.chug/configurations/[^/]+\\.json$'::text))),
    CONSTRAINT repository_configuration_repository_is_bounded CHECK (((length(repository) >= 1) AND (length(repository) <= 256))),
    CONSTRAINT repository_configuration_revision_is_bounded CHECK (((length(revision) >= 1) AND (length(revision) <= 256)))
);`,
  `CREATE TABLE public.repository_configuration_version (
    tenant text NOT NULL,
    project text NOT NULL,
    name text NOT NULL,
    digest text NOT NULL,
    number bigint NOT NULL,
    CONSTRAINT repository_configuration_version_digest_is_sha256 CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT repository_configuration_version_is_positive CHECK ((number >= 1)),
    CONSTRAINT repository_configuration_version_name_is_bounded CHECK ((((length(name) >= 1) AND (length(name) <= 128)) AND (name ~ '^[A-Za-z0-9]([A-Za-z0-9._-]*[A-Za-z0-9])?$'::text)))
);`,
  `CREATE TABLE public.scheduler_incident (
    tenant text NOT NULL,
    project text NOT NULL,
    incident text NOT NULL,
    kind text NOT NULL,
    execution text,
    attempt text,
    evidence text NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT scheduler_incident_evidence_is_bounded CHECK (((length(evidence) >= 1) AND (length(evidence) <= 1024))),
    CONSTRAINT scheduler_incident_kind_is_known CHECK ((kind = ANY (ARRAY['ConflictingResult'::text, 'ConflictingRegistration'::text, 'ImpossibleState'::text, 'CrossProjectReference'::text]))),
    CONSTRAINT scheduler_incident_subject_is_bounded CHECK ((((COALESCE(length(execution), 1) >= 1) AND (COALESCE(length(execution), 1) <= 256)) AND ((COALESCE(length(attempt), 1) >= 1) AND (COALESCE(length(attempt), 1) <= 256))))
);`,
  `CREATE TABLE public.selector_agentic_refusal (
    ordinal bigint NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    event text NOT NULL,
    ticket_version bigint NOT NULL,
    reason text NOT NULL,
    selector_decision text NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_refusal_counters_are_positive CHECK (((ticket >= 1) AND (ticket_version >= 1))),
    CONSTRAINT selector_refusal_event_is_known CHECK ((event = ANY (ARRAY['Refused'::text, 'Lifted'::text]))),
    CONSTRAINT selector_refusal_identity_is_bounded CHECK ((((length(tenant) >= 1) AND (length(tenant) <= 256)) AND ((length(project) >= 1) AND (length(project) <= 256)))),
    CONSTRAINT selector_refusal_reason_is_bounded CHECK (((length(reason) >= 1) AND (length(reason) <= 1024)))
);`,
  `CREATE TABLE public.selector_attempt (
    attempt text NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    state text NOT NULL,
    settings_revision bigint,
    observation_digest text,
    terminal_evidence text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    lease_expires_at timestamp with time zone DEFAULT now() NOT NULL,
    project_settings_revision bigint,
    CONSTRAINT selector_attempt_attempt_check CHECK (((length(attempt) >= 1) AND (length(attempt) <= 256))),
    CONSTRAINT selector_attempt_observation_digest_check CHECK (((observation_digest IS NULL) OR (observation_digest ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT selector_attempt_project_settings_revision_check CHECK (((project_settings_revision IS NULL) OR (project_settings_revision >= 0))),
    CONSTRAINT selector_attempt_settings_revision_check CHECK (((settings_revision IS NULL) OR (settings_revision >= 1))),
    CONSTRAINT selector_attempt_state_check CHECK ((state = ANY (ARRAY['Starting'::text, 'Running'::text, 'Terminating'::text, 'Completed'::text, 'Terminated'::text, 'Quarantined'::text]))),
    CONSTRAINT selector_attempt_terminal_evidence_check CHECK (((terminal_evidence IS NULL) OR ((length(terminal_evidence) >= 1) AND (length(terminal_evidence) <= 4096))))
);`,
  `CREATE TABLE public.selector_decision_permit (
    attempt text NOT NULL,
    acquired_at timestamp with time zone DEFAULT now() NOT NULL,
    released_at timestamp with time zone,
    CONSTRAINT selector_decision_permit_check CHECK (((released_at IS NULL) OR (released_at >= acquired_at)))
);`,
  `CREATE TABLE public.selector_interaction (
    selector_decision text NOT NULL,
    ordinal bigint NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    instructions_version text NOT NULL,
    instructions text NOT NULL,
    observed_view text NOT NULL,
    context text NOT NULL,
    tool_activity text NOT NULL,
    result text NOT NULL,
    implementation_revision text NOT NULL,
    model_revision text NOT NULL,
    policy_revision text NOT NULL,
    accounting text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    observed_token text,
    CONSTRAINT selector_interaction_check CHECK ((((length(instructions_version) >= 1) AND (length(instructions_version) <= 256)) AND ((length(implementation_revision) >= 1) AND (length(implementation_revision) <= 256)) AND ((length(model_revision) >= 1) AND (length(model_revision) <= 256)) AND ((length(policy_revision) >= 1) AND (length(policy_revision) <= 256)))),
    CONSTRAINT selector_interaction_check1 CHECK (((length(instructions) <= 65536) AND (length(observed_view) <= 65536) AND (length(context) <= 65536) AND (length(tool_activity) <= 65536) AND (length(result) <= 65536) AND (length(accounting) <= 65536))),
    CONSTRAINT selector_interaction_check2 CHECK ((completed_at >= started_at)),
    CONSTRAINT selector_interaction_selector_decision_check CHECK (((length(selector_decision) >= 1) AND (length(selector_decision) <= 256)))
);`,
  `CREATE TABLE public.selector_interaction_resource (
    selector_decision text NOT NULL,
    kind text NOT NULL,
    ordinal bigint NOT NULL,
    digest text NOT NULL,
    byte_length bigint NOT NULL,
    chunk_count bigint NOT NULL,
    content text NOT NULL,
    CONSTRAINT selector_interaction_resource_check CHECK (((ordinal >= 0) AND (byte_length >= 0) AND (chunk_count >= 1))),
    CONSTRAINT selector_interaction_resource_content_check CHECK ((length(content) <= 65536)),
    CONSTRAINT selector_interaction_resource_digest_check CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT selector_interaction_resource_kind_check CHECK ((kind = ANY (ARRAY['ObservedView'::text, 'Context'::text, 'ToolActivity'::text])))
);`,
  `CREATE TABLE public.selector_inventory_state (
    singleton integer DEFAULT 1 NOT NULL,
    tenant text,
    project text,
    CONSTRAINT selector_inventory_state_check CHECK (((tenant IS NULL) = (project IS NULL))),
    CONSTRAINT selector_inventory_state_singleton_check CHECK ((singleton = 1))
);`,
  `CREATE TABLE public.selector_observation (
    attempt text NOT NULL,
    observation text NOT NULL,
    manifest_digest text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_observation_manifest_digest_check CHECK ((manifest_digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT selector_observation_observation_check CHECK (((length(observation) >= 2) AND (length(observation) <= 2097152)))
);`,
  `CREATE TABLE public.selector_planning_intent (
    tenant text NOT NULL,
    project text NOT NULL,
    selector_decision text NOT NULL,
    intent text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_planning_intent_intent_check CHECK ((length(intent) <= 65536))
);`,
  `CREATE TABLE public.selector_project_settings (
    tenant text NOT NULL,
    project text NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    north_star text,
    mode text,
    dispatch_mode text,
    base_prompt text,
    model_allowlist text,
    tool_allowlist text,
    tokens_per_decision bigint,
    milliseconds_per_decision bigint,
    tool_calls_per_decision bigint,
    input_bytes_per_decision bigint,
    candidate_pages_per_decision bigint,
    operational_context_max_age_ms bigint,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    dispatches_per_decision bigint,
    thread_standing_rules text,
    CONSTRAINT selector_project_dispatches_are_bounded CHECK (((dispatches_per_decision IS NULL) OR ((dispatches_per_decision >= 1) AND (dispatches_per_decision <= 8)))),
    CONSTRAINT selector_project_settings_base_prompt_check CHECK (((base_prompt IS NULL) OR ((length(base_prompt) >= 1) AND (length(base_prompt) <= 65536)))),
    CONSTRAINT selector_project_settings_candidate_pages_per_decision_check CHECK (((candidate_pages_per_decision IS NULL) OR (candidate_pages_per_decision >= 1))),
    CONSTRAINT selector_project_settings_dispatch_mode_check CHECK (((dispatch_mode IS NULL) OR (dispatch_mode = ANY (ARRAY['Automatic'::text, 'ApprovalRequired'::text])))),
    CONSTRAINT selector_project_settings_input_bytes_per_decision_check CHECK (((input_bytes_per_decision IS NULL) OR (input_bytes_per_decision >= 1))),
    CONSTRAINT selector_project_settings_milliseconds_per_decision_check CHECK (((milliseconds_per_decision IS NULL) OR (milliseconds_per_decision >= 1))),
    CONSTRAINT selector_project_settings_mode_check CHECK (((mode IS NULL) OR (mode = ANY (ARRAY['Running'::text, 'Paused'::text])))),
    CONSTRAINT selector_project_settings_model_allowlist_check CHECK (((model_allowlist IS NULL) OR ((length(model_allowlist) >= 2) AND (length(model_allowlist) <= 65536)))),
    CONSTRAINT selector_project_settings_north_star_check CHECK (((north_star IS NULL) OR ((length(north_star) >= 1) AND (length(north_star) <= 65536)))),
    CONSTRAINT selector_project_settings_operational_context_max_age_ms_check CHECK (((operational_context_max_age_ms IS NULL) OR (operational_context_max_age_ms >= 1))),
    CONSTRAINT selector_project_settings_revision_check CHECK ((revision >= 1)),
    CONSTRAINT selector_project_settings_tokens_per_decision_check CHECK (((tokens_per_decision IS NULL) OR (tokens_per_decision >= 1))),
    CONSTRAINT selector_project_settings_tool_allowlist_check CHECK (((tool_allowlist IS NULL) OR ((length(tool_allowlist) >= 2) AND (length(tool_allowlist) <= 65536)))),
    CONSTRAINT selector_project_settings_tool_calls_per_decision_check CHECK (((tool_calls_per_decision IS NULL) OR (tool_calls_per_decision >= 1))),
    CONSTRAINT selector_project_thread_standing_rules_is_bounded CHECK (((thread_standing_rules IS NULL) OR ((length(thread_standing_rules) >= 1) AND (length(thread_standing_rules) <= 65536))))
);`,
  `CREATE TABLE public.selector_project_settings_history (
    tenant text NOT NULL,
    project text NOT NULL,
    revision bigint NOT NULL,
    north_star text,
    mode text,
    dispatch_mode text,
    base_prompt text,
    model_allowlist text,
    tool_allowlist text,
    tokens_per_decision bigint,
    milliseconds_per_decision bigint,
    tool_calls_per_decision bigint,
    input_bytes_per_decision bigint,
    candidate_pages_per_decision bigint,
    operational_context_max_age_ms bigint,
    administrator_kind text NOT NULL,
    administrator_subject text CONSTRAINT selector_project_settings_histor_administrator_subject_not_null NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    dispatches_per_decision bigint,
    thread_standing_rules text,
    CONSTRAINT selector_project_settings_history_administrator_kind_check CHECK (((length(administrator_kind) >= 1) AND (length(administrator_kind) <= 256))),
    CONSTRAINT selector_project_settings_history_administrator_subject_check CHECK (((length(administrator_subject) >= 1) AND (length(administrator_subject) <= 256))),
    CONSTRAINT selector_project_settings_history_revision_check CHECK ((revision >= 1))
);`,
  `CREATE TABLE public.selector_project_state (
    tenant text NOT NULL,
    project text NOT NULL,
    notification_cursor bigint DEFAULT 0 NOT NULL,
    recovery_epoch text,
    attention text DEFAULT 'Monitoring'::text NOT NULL,
    revision bigint DEFAULT 0 NOT NULL,
    candidate_scan_token text,
    candidate_scan_after bigint,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    handoff_note text DEFAULT '{}'::text CONSTRAINT selector_project_state_working_memory_not_null NOT NULL,
    candidate_scan_state text DEFAULT 'Unstarted'::text NOT NULL,
    candidate_scan_exhausted_token text,
    CONSTRAINT selector_project_state_attention_check CHECK ((attention = ANY (ARRAY['Monitoring'::text, 'Attention'::text, 'Stopped'::text]))),
    CONSTRAINT selector_project_state_candidate_scan_after_check CHECK (((candidate_scan_after IS NULL) OR (candidate_scan_after >= 1))),
    CONSTRAINT selector_project_state_candidate_scan_exhausted_token_check CHECK (((candidate_scan_exhausted_token IS NULL) OR (length(candidate_scan_exhausted_token) <= 65536))),
    CONSTRAINT selector_project_state_candidate_scan_state_check CHECK ((candidate_scan_state = ANY (ARRAY['Unstarted'::text, 'Continue'::text, 'Exhausted'::text]))),
    CONSTRAINT selector_project_state_candidate_scan_token_check CHECK (((candidate_scan_token IS NULL) OR (length(candidate_scan_token) <= 65536))),
    CONSTRAINT selector_project_state_check CHECK (((notification_cursor >= 0) AND (revision >= 0))),
    CONSTRAINT selector_project_state_check1 CHECK (((candidate_scan_token IS NULL) = (candidate_scan_after IS NULL))),
    CONSTRAINT selector_project_state_recovery_epoch_check CHECK (((recovery_epoch IS NULL) OR ((length(recovery_epoch) >= 1) AND (length(recovery_epoch) <= 256)))),
    CONSTRAINT selector_project_state_working_memory_check CHECK ((length(handoff_note) <= 65536))
);`,
  `CREATE TABLE public.selector_proposal_delivery (
    selector_decision text NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    operation text NOT NULL,
    command text NOT NULL,
    state text DEFAULT 'Pending'::text NOT NULL,
    outcome text,
    attempts bigint DEFAULT 0 NOT NULL,
    retry_at timestamp with time zone DEFAULT now() NOT NULL,
    reconcile_at timestamp with time zone,
    reconciliation_attempts bigint DEFAULT 0 NOT NULL,
    ticket bigint NOT NULL,
    CONSTRAINT selector_proposal_delivery_attempts_check CHECK ((attempts >= 0)),
    CONSTRAINT selector_proposal_delivery_check CHECK ((((length(operation) >= 1) AND (length(operation) <= 256)) AND (length(command) <= 65536) AND ((outcome IS NULL) OR (length(outcome) <= 65536)))),
    CONSTRAINT selector_proposal_delivery_reconciliation_attempts_check CHECK ((reconciliation_attempts >= 0)),
    CONSTRAINT selector_proposal_delivery_state_check CHECK ((state = ANY (ARRAY['AwaitingApproval'::text, 'Pending'::text, 'Submitted'::text, 'Terminal'::text]))),
    CONSTRAINT selector_proposal_ticket_is_positive CHECK ((ticket >= 1))
);`,
  `CREATE TABLE public.selector_proposal_review (
    ordinal bigint NOT NULL,
    selector_decision text NOT NULL,
    tenant text NOT NULL,
    project text NOT NULL,
    outcome text NOT NULL,
    reviewer_kind text NOT NULL,
    reviewer_subject text NOT NULL,
    feedback text,
    reviewed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_proposal_review_feedback_check CHECK (((feedback IS NULL) OR (length(feedback) <= 65536))),
    CONSTRAINT selector_proposal_review_outcome_check CHECK ((outcome = ANY (ARRAY['Approved'::text, 'Rejected'::text]))),
    CONSTRAINT selector_proposal_review_reviewer_kind_check CHECK (((length(reviewer_kind) >= 1) AND (length(reviewer_kind) <= 256))),
    CONSTRAINT selector_proposal_review_reviewer_subject_check CHECK (((length(reviewer_subject) >= 1) AND (length(reviewer_subject) <= 256)))
);`,
  `CREATE TABLE public.selector_runtime_readiness (
    singleton integer DEFAULT 1 NOT NULL,
    production_host boolean DEFAULT false NOT NULL,
    checked_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_runtime_readiness_singleton_check CHECK ((singleton = 1))
);`,
  `CREATE TABLE public.selector_runtime_settings (
    singleton integer DEFAULT 1 NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    mode text DEFAULT 'Running'::text NOT NULL,
    dispatch_mode text DEFAULT 'ApprovalRequired'::text NOT NULL,
    base_prompt text NOT NULL,
    controls text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_runtime_settings_check CHECK ((((length(base_prompt) >= 1) AND (length(base_prompt) <= 65536)) AND ((length(controls) >= 2) AND (length(controls) <= 65536)))),
    CONSTRAINT selector_runtime_settings_dispatch_mode_check CHECK ((dispatch_mode = ANY (ARRAY['Automatic'::text, 'ApprovalRequired'::text]))),
    CONSTRAINT selector_runtime_settings_mode_check CHECK ((mode = ANY (ARRAY['Running'::text, 'Paused'::text]))),
    CONSTRAINT selector_runtime_settings_revision_check CHECK ((revision >= 1)),
    CONSTRAINT selector_runtime_settings_singleton_check CHECK ((singleton = 1))
);`,
  `CREATE TABLE public.selector_runtime_settings_history (
    revision bigint NOT NULL,
    mode text NOT NULL,
    dispatch_mode text NOT NULL,
    base_prompt text NOT NULL,
    controls text NOT NULL,
    administrator_kind text NOT NULL,
    administrator_subject text CONSTRAINT selector_runtime_settings_histor_administrator_subject_not_null NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT selector_runtime_settings_history_administrator_kind_check CHECK (((length(administrator_kind) >= 1) AND (length(administrator_kind) <= 256))),
    CONSTRAINT selector_runtime_settings_history_administrator_subject_check CHECK (((length(administrator_subject) >= 1) AND (length(administrator_subject) <= 256))),
    CONSTRAINT selector_runtime_settings_history_check CHECK ((((length(base_prompt) >= 1) AND (length(base_prompt) <= 65536)) AND ((length(controls) >= 2) AND (length(controls) <= 65536)))),
    CONSTRAINT selector_runtime_settings_history_dispatch_mode_check CHECK ((dispatch_mode = ANY (ARRAY['Automatic'::text, 'ApprovalRequired'::text]))),
    CONSTRAINT selector_runtime_settings_history_mode_check CHECK ((mode = ANY (ARRAY['Running'::text, 'Paused'::text]))),
    CONSTRAINT selector_runtime_settings_history_revision_check CHECK ((revision >= 1))
);`,
  `CREATE TABLE public.session_attempt (
    tenant text NOT NULL,
    project text NOT NULL,
    session text NOT NULL,
    attempt text NOT NULL,
    attempt_number bigint NOT NULL,
    generation bigint DEFAULT 1 NOT NULL,
    recovery_epoch text NOT NULL,
    state text DEFAULT 'Placing'::text NOT NULL,
    lease_owner text,
    lease_expires_at timestamp with time zone,
    placement text,
    evidence text,
    bearer text NOT NULL,
    bearer_secret_digest text NOT NULL,
    idle_since timestamp with time zone,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    cleanup_completed_at timestamp with time zone,
    CONSTRAINT session_attempt_counters_are_positive CHECK (((attempt_number >= 1) AND (generation >= 1))),
    CONSTRAINT session_attempt_digest_is_sha256 CHECK ((bearer_secret_digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT session_attempt_ending_is_whole CHECK (((state = ANY (ARRAY['Placing'::text, 'Running'::text])) = (ended_at IS NULL))),
    CONSTRAINT session_attempt_evidence_is_known CHECK (((evidence IS NULL) OR (evidence = ANY (ARRAY['PolicyDenied'::text, 'PolicyUnavailable'::text, 'PlacementDenied'::text, 'PlacementUnavailable'::text, 'Evicted'::text, 'Vanished'::text, 'LeaseExpired'::text, 'Fenced'::text, 'SessionIdle'::text, 'SessionClosed'::text, 'TurnFailed'::text, 'StoreRefused'::text, 'AgentRateLimited'::text])))),
    CONSTRAINT session_attempt_evidence_is_whole CHECK (((evidence IS NULL) OR (state <> ALL (ARRAY['Placing'::text, 'Running'::text])))),
    CONSTRAINT session_attempt_lease_is_whole CHECK (((lease_owner IS NULL) = (lease_expires_at IS NULL))),
    CONSTRAINT session_attempt_state_is_known CHECK ((state = ANY (ARRAY['Placing'::text, 'Running'::text, 'Reported'::text, 'Lost'::text, 'Withdrawn'::text, 'Superseded'::text]))),
    CONSTRAINT session_attempt_text_is_bounded CHECK ((((length(attempt) >= 1) AND (length(attempt) <= 256)) AND ((length(bearer) >= 1) AND (length(bearer) <= 256)) AND ((COALESCE(length(lease_owner), 1) >= 1) AND (COALESCE(length(lease_owner), 1) <= 256)) AND ((COALESCE(length(placement), 1) >= 1) AND (COALESCE(length(placement), 1) <= 256))))
);`,
  `CREATE TABLE public.session_store_batch (
    tenant text NOT NULL,
    project text NOT NULL,
    session text NOT NULL,
    stream text NOT NULL,
    batch bigint NOT NULL,
    digest text NOT NULL,
    bytes bigint NOT NULL,
    events bigint NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT session_store_batch_is_bounded CHECK ((((batch >= 1) AND (batch <= 65536)) AND ((bytes >= 0) AND (bytes <= 65536)) AND ((events >= 0) AND (events <= 65536)))),
    CONSTRAINT session_store_object_is_bounded CHECK (((digest ~ '^[0-9a-f]{64}$'::text) AND ((length(stream) >= 1) AND (length(stream) <= 256)) AND (stream !~ '[[:cntrl:]]'::text) AND (stream !~ '[[:space:]]'::text)))
);`,
  `CREATE TABLE public.session_turn (
    tenant text NOT NULL,
    project text NOT NULL,
    session text NOT NULL,
    turn text NOT NULL,
    ordinal bigint NOT NULL,
    input_kind text NOT NULL,
    input text NOT NULL,
    state text DEFAULT 'Queued'::text NOT NULL,
    attempt text,
    claim_generation bigint,
    attempts_spent bigint DEFAULT 0 NOT NULL,
    result text,
    failure text,
    batch_first bigint,
    batch_last bigint,
    enqueued_at timestamp with time zone DEFAULT now() NOT NULL,
    claimed_at timestamp with time zone,
    ended_at timestamp with time zone,
    model text,
    tokens bigint,
    cost_micros bigint,
    duration_ms bigint,
    tools text[],
    CONSTRAINT session_turn_batches_are_whole CHECK ((((batch_first IS NULL) = (batch_last IS NULL)) AND (COALESCE(batch_first, (1)::bigint) <= COALESCE(batch_last, (1)::bigint)))),
    CONSTRAINT session_turn_claim_is_whole CHECK ((((state = 'Claimed'::text) = (attempt IS NOT NULL)) AND ((attempt IS NULL) = (claim_generation IS NULL)) AND ((state = 'Claimed'::text) = (claimed_at IS NOT NULL)))),
    CONSTRAINT session_turn_counters_are_bounded CHECK ((((ordinal >= 1) AND (ordinal <= 100000)) AND ((attempts_spent >= 0) AND (attempts_spent <= 3)) AND ((COALESCE(batch_first, (1)::bigint) >= 1) AND (COALESCE(batch_first, (1)::bigint) <= 65536)) AND ((COALESCE(batch_last, (1)::bigint) >= 1) AND (COALESCE(batch_last, (1)::bigint) <= 65536)))),
    CONSTRAINT session_turn_ending_is_whole CHECK ((((state = ANY (ARRAY['Answered'::text, 'Failed'::text, 'Abandoned'::text])) = (ended_at IS NOT NULL)) AND ((state = 'Answered'::text) = (result IS NOT NULL)) AND ((state = ANY (ARRAY['Failed'::text, 'Abandoned'::text])) = (failure IS NOT NULL)))),
    CONSTRAINT session_turn_failure_is_known CHECK (((failure IS NULL) OR (failure = ANY (ARRAY['AgentFailed'::text, 'AgentRateLimited'::text, 'AgentTurnsExhausted'::text, 'AgentBudgetExhausted'::text, 'StoreRefused'::text, 'AttemptLost'::text, 'SessionClosed'::text, 'TurnWithdrawn'::text])))),
    CONSTRAINT session_turn_identity_is_bounded CHECK (((length(turn) >= 1) AND (length(turn) <= 256))),
    CONSTRAINT session_turn_kind_is_known CHECK ((input_kind = ANY (ARRAY['Observation'::text, 'UserMessage'::text, 'Wake'::text, 'Inquiry'::text]))),
    CONSTRAINT session_turn_measure_is_bounded CHECK (((COALESCE(tokens, (0)::bigint) >= 0) AND (COALESCE(cost_micros, (0)::bigint) >= 0) AND (COALESCE(duration_ms, (0)::bigint) >= 0) AND ((COALESCE(length(model), 1) >= 1) AND (COALESCE(length(model), 1) <= 256)) AND (COALESCE(cardinality(tools), 0) <= 64) AND (COALESCE(length(array_to_string(tools, ','::text)), 0) <= 8256))),
    CONSTRAINT session_turn_measure_is_whole CHECK ((((model IS NULL) = (tokens IS NULL)) AND ((model IS NULL) = (cost_micros IS NULL)) AND ((model IS NULL) = (duration_ms IS NULL)) AND ((model IS NULL) = (tools IS NULL)))),
    CONSTRAINT session_turn_state_is_known CHECK ((state = ANY (ARRAY['Queued'::text, 'Claimed'::text, 'Answered'::text, 'Failed'::text, 'Abandoned'::text]))),
    CONSTRAINT session_turn_text_is_bounded CHECK ((((length(input) >= 1) AND (length(input) <= 17525063)) AND (COALESCE(length(result), 0) <= 65536)))
);`,
  `CREATE TABLE public.thread_wake_cursor (
    singleton boolean DEFAULT true NOT NULL,
    sequence bigint DEFAULT 0 NOT NULL,
    CONSTRAINT thread_wake_cursor_is_not_negative CHECK ((sequence >= 0)),
    CONSTRAINT thread_wake_cursor_is_one_row CHECK (singleton)
);`,
  `CREATE TABLE public.ticket_projection (
    tenant text NOT NULL,
    project text NOT NULL,
    ticket bigint NOT NULL,
    phase text NOT NULL,
    seq bigint NOT NULL,
    configuration_revision text,
    configuration_digest text,
    dependable boolean DEFAULT true NOT NULL,
    reason text DEFAULT 'NoReason'::text NOT NULL,
    resume_at text,
    gas_left bigint,
    rework_left bigint,
    finalization_left bigint,
    CONSTRAINT ticket_projection_accounts_are_not_negative CHECK (((COALESCE(gas_left, (0)::bigint) >= 0) AND (COALESCE(rework_left, (0)::bigint) >= 0) AND (COALESCE(finalization_left, (0)::bigint) >= 0))),
    CONSTRAINT ticket_projection_accounts_are_whole CHECK ((((gas_left IS NULL) = (rework_left IS NULL)) AND ((gas_left IS NOT NULL) OR (finalization_left IS NULL)))),
    CONSTRAINT ticket_projection_configuration_is_whole CHECK (((configuration_revision IS NULL) = (configuration_digest IS NULL))),
    CONSTRAINT ticket_projection_counters_are_positive CHECK (((ticket >= 1) AND (seq >= 1))),
    CONSTRAINT ticket_projection_phase_is_known CHECK ((phase = ANY (ARRAY['Pending'::text, 'Working'::text, 'Evaluating'::text, 'Finalizing'::text, 'PublishingHandoff'::text, 'HandoffBlocked'::text, 'Done'::text, 'Abandoned'::text, 'Escalated'::text, 'Revoked'::text]))),
    CONSTRAINT ticket_projection_reason_is_known CHECK ((reason = ANY (ARRAY['NoReason'::text, 'WorkFailed'::text, 'ReworkBudgetExhausted'::text, 'FinalizationBudgetExhausted'::text, 'GasExhausted'::text, 'DependencyRevoked'::text, 'ExecutionPolicyDenied'::text, 'TicketConfigIncompatible'::text, 'ExecutionProfileUnavailable'::text, 'RuntimeVersionUnsupported'::text, 'RequiredCapabilityUnavailable'::text]))),
    CONSTRAINT ticket_projection_resume_is_known CHECK (((resume_at IS NULL) OR (resume_at = ANY (ARRAY['NoResume'::text, 'ResumeWorking'::text, 'ResumeReworking'::text, 'ResumeEvaluating'::text, 'ResumeFinalizing'::text, 'ResumePublishingHandoff'::text]))))
);`,
  `CREATE TABLE public.worker_artifact_reservation (
    tenant text NOT NULL,
    project text NOT NULL,
    execution text NOT NULL,
    attempt text NOT NULL,
    path text NOT NULL,
    digest text NOT NULL,
    bytes bigint NOT NULL,
    CONSTRAINT worker_artifact_reservation_bytes_check CHECK (((bytes >= 0) AND (bytes <= 1073741824))),
    CONSTRAINT worker_artifact_reservation_digest_check CHECK ((digest ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT worker_artifact_reservation_path_check CHECK ((((length(path) >= 1) AND (length(path) <= 256)) AND (path !~ '^/'::text) AND (path !~ '//'::text) AND (path !~ '[\\\\]'::text) AND (path !~ '(^|/)[.][.]?(/|$)'::text) AND (path !~ '[[:cntrl:]]'::text) AND (path !~ '(^|/)[[:space:]]'::text) AND (path !~ '[[:space:]](/|$)'::text)))
);`,
];
