/**
 * Entries copied verbatim from `test/fixtures/sessionStore/`, less the
 * runtime's bookkeeping lines and with each backslash doubled for the literal
 * that holds them. They are a copy because a console suite may not reach
 * outside `ui/` — `check-boundaries.sh`, `console-reaches-no-source` — and
 * hand-written blocks would prove the parser against what its author expected
 * rather than against what the store writes.
 */

import {
  conversationBlocksOf,
  type ConversationEntry,
  type ConversationItem,
} from "../app/core/conversation.ts";

const conversationStoreLines = `
{"uuid":"105764be-afd3-4bc5-b902-b0d6329efe4d","type":"user","timestamp":"2026-09-02T15:46:15.317Z","message":{"role":"user","content":[{"type":"text","text":"Remember the word NARWHAL and reply ok"}]}}
{"uuid":"49d03778-65ab-4d0a-a132-76047016ed81","type":"assistant","timestamp":"2026-09-02T15:46:16.920Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesakKm3chfd5xTdv5qq","type":"message","role":"assistant","content":[{"type":"thinking","thinking":"The user is asking me to remember the word \\"NARWHAL\\" and reply \\"ok\\". This is a straightforward request. I should acknowledge that I've noted this word and respond with \\"ok\\".","signature":"EsMDCrIBCBEYAipAZU6G/6mcO+AVW+ZWkOhN3vNOVZ3xUHBXPonKARKts6DDqnreNR7J8HeqvO0fLDCfbHaSkHAbDOnZXWS4OMcY9zIZY2xhdWRlLWhhaWt1LTQtNS0yMDI1MTAwMTgAQgh0aGlua2luZ1okMzNjYTExOTItZTYzYi00MjJjLWI0ZGUtZTZhMTg3MjgyZTM5chDsmE8h0xwz5v8wVrFI+3aZiAEBqAHIieHUBrABAhIMpqmY3tBGMySp+fcqGgzx7QRoXTnR5rhYRxwiMNm/nE1rc0kuua19yXu6vOa0cA31dVy+ZiQsF+Ub0xrF8QRikBgO1r9UZhO7yScHBSq9ATZFOCNLH/kzaQuyFsC/F1673KabB0+WUi9rxgF1hYWjn/X6y1d9qqwWOk5SZbj9UXrqxFZ6kMUJ0zpGLVOs8XDvfMHNVt8k5YtR6Vfum5x5Bbq7N6+ZUSVF9oYzNak35nQb/7bjSOSaxy3c8CL9w47qEf/CgJlyaKmPCi7LBhw+dVwgLwBFgoF6K7tpMCCS59okcx0/XVZ4J5w6FHx1046LCD9IPVjX7Rf19cyzxVlMTLnZqqj/Z7sHP69iDBgB"}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":14622,"cache_read_input_tokens":0,"output_tokens":66,"output_tokens_details":{"thinking_tokens":47},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":14622,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":66,"cache_read_input_tokens":0,"cache_creation_input_tokens":14622,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":14622},"type":"message"}],"speed":"standard"},"diagnostics":null}}
{"uuid":"2610f5bb-2423-4f26-85c9-428f39e2f332","type":"assistant","timestamp":"2026-09-02T15:46:16.935Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesakKm3chfd5xTdv5qq","type":"message","role":"assistant","content":[{"type":"text","text":"I've noted the word **NARWHAL**. \\n\\nOk"}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":14622,"cache_read_input_tokens":0,"output_tokens":66,"output_tokens_details":{"thinking_tokens":47},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":14622,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":66,"cache_read_input_tokens":0,"cache_creation_input_tokens":14622,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":14622},"type":"message"}],"speed":"standard"},"diagnostics":null}}
{"uuid":"7eab7ca0-8c4b-4667-beb4-f8725e4652ad","type":"user","timestamp":"2026-09-02T15:46:25.287Z","message":{"role":"user","content":[{"type":"text","text":"What word did I ask you to remember? Reply with just that word."}]}}
{"uuid":"90cecf93-257c-43b0-ac37-1609e63da558","type":"assistant","timestamp":"2026-09-02T15:46:26.670Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesbV1YQ3pycw3YinSNT","type":"message","role":"assistant","content":[{"type":"thinking","thinking":"The user asked me to remember the word \\"NARWHAL\\" in the previous message. Now they're asking me to recall it and reply with just that word.","signature":"EqEDCrIBCBEYAipA7QNfIUiCcYK9jqbMgS+i2fBUFboUe1IPNzG0wJ3y1ak0K7hSF7sIrr967JWhJqpdmf/cSUQ1VjxymgcUSVyedTIZY2xhdWRlLWhhaWt1LTQtNS0yMDI1MTAwMTgAQgh0aGlua2luZ1okMzNjYTExOTItZTYzYi00MjJjLWI0ZGUtZTZhMTg3MjgyZTM5chDsmE8h0xwz5v8wVrFI+3aZiAEBqAHSieHUBrABAhIMlSz16EdSE2u5lf+6Ggyq9nsD0MGyrrboQ20iMP6OWVU3VXkhrzEBa9YsUi008g4XMlU3BSCwDdn/zSdmmMsizALRUifa307JxJ3EfiqbAR8QrBGnjpHaakMUy/+ZckGRDiYHfdklrmnyF4A7t9qz4TR3s7aR8x85urZniaXdkJ2685cg1uf/WdOfwBfILApsTvdqTz4/cWtrYygpKHFVW6JBMJKD++3Lj897Txx8CsgcFRnoFDo8AXKRyAxd8FtqLSZXgSmqojN9MNsm98nLhFq4GPboSMtVqsP/u2Ed8Aj2C7ds+lvoK0jPGAE="}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":120,"cache_read_input_tokens":14622,"output_tokens":47,"output_tokens_details":{"thinking_tokens":38},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":120,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":47,"cache_read_input_tokens":14622,"cache_creation_input_tokens":120,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":120},"type":"message"}],"speed":"standard"},"diagnostics":null}}
{"uuid":"40644f4d-642f-428e-a762-f16e8b5889b9","type":"assistant","timestamp":"2026-09-02T15:46:26.672Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesbV1YQ3pycw3YinSNT","type":"message","role":"assistant","content":[{"type":"text","text":"NARWHAL"}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":120,"cache_read_input_tokens":14622,"output_tokens":47,"output_tokens_details":{"thinking_tokens":38},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":120,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":47,"cache_read_input_tokens":14622,"cache_creation_input_tokens":120,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":120},"type":"message"}],"speed":"standard"},"diagnostics":null}}
{"uuid":"ac630817-7d51-48b3-b7e9-1f02abfb78d8","type":"user","timestamp":"2026-09-02T15:46:49.337Z","message":{"role":"user","content":[{"type":"text","text":"What word did I ask you to remember? Reply with just that word."}]}}
{"uuid":"1d5e0e32-77f1-4389-bc18-3dbeecc73768","type":"assistant","timestamp":"2026-09-02T15:46:50.653Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesdGL73nkVT8uhHwHGC","type":"message","role":"assistant","content":[{"type":"thinking","thinking":"The user is asking me again what word they asked me to remember. In the first message, they asked me to remember the word \\"NARWHAL\\". I should reply with just that word.","signature":"Er4DCrIBCBEYAipA6QwZs2Rs0QmKoMoWfGsptLZUrQh/+6ym3HnkdL1Fm7FXqX5CRunuP34YgSGQEbn9MNwrATebfUC6T1SMG2WW/zIZY2xhdWRlLWhhaWt1LTQtNS0yMDI1MTAwMTgAQgh0aGlua2luZ1okMzNjYTExOTItZTYzYi00MjJjLWI0ZGUtZTZhMTg3MjgyZTM5chDsmE8h0xwz5v8wVrFI+3aZiAEBqAHqieHUBrABAhIMIkE5TEfQyyYzNLblGgwPYZp+OVfcCrN0/rAiMNnPKEewnGDl07Gb4fKO849QJSx8nAy7eCi6PMSAJ12u83lcDezeiweljCp6nI2IoCq4AT7JbUj1j/OJxFZhJBY108FRBB+jxm1v8hoSDX4QW/p8YQ+nh+zE5ZclDhp0hCpTh38Ase74FNtjK7UfMJv+QYOnkViZxwr0mnPi29nLLvyuCCfUCsP1+VbHY38488eJlvHWKOyn3dRuRQ7828yf8HDHR2Miyum0pmK4CvYtm8MZW2QAiTX2mbOqODXExeZz94A+VAwRUb9/SVWxoBp2rc81RIwNKfQyHNXHWzptufIWRIkk6O1CJ1wYAQ=="}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":101,"cache_read_input_tokens":14742,"output_tokens":53,"output_tokens_details":{"thinking_tokens":44},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":101,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":53,"cache_read_input_tokens":14742,"cache_creation_input_tokens":101,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":101},"type":"message"}],"speed":"standard"},"diagnostics":null}}
{"uuid":"248f9768-f053-4b69-bf49-aa2ddaef8475","type":"assistant","timestamp":"2026-09-02T15:46:50.655Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesdGL73nkVT8uhHwHGC","type":"message","role":"assistant","content":[{"type":"text","text":"NARWHAL"}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":101,"cache_read_input_tokens":14742,"output_tokens":53,"output_tokens_details":{"thinking_tokens":44},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":101,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":53,"cache_read_input_tokens":14742,"cache_creation_input_tokens":101,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":101},"type":"message"}],"speed":"standard"},"diagnostics":null}}
{"uuid":"d9523fb8-9824-406d-9d34-5352e03c79ef","type":"user","timestamp":"2026-09-02T15:46:56.238Z","message":{"role":"user","content":[{"type":"text","text":"What word did I ask you to remember? Reply with just that word."}]}}
{"uuid":"908e5b0d-97bf-4722-9b53-e0ea8a283d41","type":"assistant","timestamp":"2026-09-02T15:46:57.578Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesdmCBqiHuybMsLUAYV","type":"message","role":"assistant","content":[{"type":"thinking","thinking":"The user is asking me what word they asked me to remember. Looking back at the conversation, in the very first message, the user said: \\"Remember the word NARWHAL and reply ok\\"\\n\\nSo the word they asked me to remember is NARWHAL.","signature":"EvgDCrIBCBEYAipACWshLGeyRezSx7HfFj/cqZtOcJb05VrTCWMIXGBX9/p6vZMb0sbVEL8jdskzFcWfUiunLVXnqFdrCc8K2qOsezIZY2xhdWRlLWhhaWt1LTQtNS0yMDI1MTAwMTgAQgh0aGlua2luZ1okMzNjYTExOTItZTYzYi00MjJjLWI0ZGUtZTZhMTg3MjgyZTM5chDsmE8h0xwz5v8wVrFI+3aZiAEBqAHxieHUBrABAhIModt//iVkmO3hEHcwGgyaRn3CNr0AW8h/chUiMH9FEVFxBL7Hksh4e3op8zMwPRAeOsM91pstCGshPc/Tg7hS9xv3eDXk5ARxEvYjrCryAZYvnHwgZnyF6GnS11x3hEKT0R5yBU9j5F2YkSqxdk7zN+pUAhLQsByjrKieAKV0yD1LKz74VRDNFcP9QyuedRHtM53SwHcwh4gyF6Lrfb01EwrUd/rbM+gSkZe3l6VjnofIqPDAiCVM9AsILgdJmo4kVfSxzP6/KYbIBiA8p8yszHXF5VSF6ou2KvdrtGFNcBOY8CcNdYBm/6LPIs6yJCwkGRfX3Ck93Bus2jYrgppSG8xtxhUR/eQqAybA4EOIkoAJMp+XNzj2pBYgiIfsrK5UetxQVARCfuSZinroNuJ0xYhmIGIYpTjo3/qO36Zi0LCnGAE="}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":3643,"cache_read_input_tokens":11311,"output_tokens":71,"output_tokens_details":{"thinking_tokens":61},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":3643,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":71,"cache_read_input_tokens":11311,"cache_creation_input_tokens":3643,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":3643},"type":"message"}],"speed":"standard"},"diagnostics":{"cache_miss_reason":{"type":"messages_changed","cache_missed_input_tokens":3501}}}}
{"uuid":"155c3c01-aeea-4312-ab8a-68b553c15903","type":"assistant","timestamp":"2026-09-02T15:46:57.580Z","message":{"model":"claude-haiku-4-5-20251001","id":"msg_011CeesdmCBqiHuybMsLUAYV","type":"message","role":"assistant","content":[{"type":"text","text":"NARWHAL"}],"stop_reason":"end_turn","stop_sequence":null,"stop_details":null,"usage":{"input_tokens":10,"cache_creation_input_tokens":3643,"cache_read_input_tokens":11311,"output_tokens":71,"output_tokens_details":{"thinking_tokens":61},"server_tool_use":{"web_search_requests":0,"web_fetch_requests":0},"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":3643,"ephemeral_5m_input_tokens":0},"inference_geo":"not_available","iterations":[{"input_tokens":10,"output_tokens":71,"cache_read_input_tokens":11311,"cache_creation_input_tokens":3643,"cache_creation":{"ephemeral_5m_input_tokens":0,"ephemeral_1h_input_tokens":3643},"type":"message"}],"speed":"standard"},"diagnostics":{"cache_miss_reason":{"type":"messages_changed","cache_missed_input_tokens":3501}}}}
{"uuid":"83738f97-737d-412f-8a49-3c56c4a78ef9","type":"system","subtype":"compact_boundary","timestamp":"2026-09-02T15:48:54.703Z"}
{"uuid":"3dac513c-ce7f-4064-852d-fa43d71830cd","type":"user","timestamp":"2026-09-02T15:48:54.702Z","message":{"role":"user","content":"This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation.\\n\\nSummary:\\n1. Primary Request and Intent:\\n   The user's primary intent has evolved across the conversation. Initially, they asked me to remember the word \\"NARWHAL.\\" This was followed by three successive requests to recall that word, with the final request contradicted by detailed instructions to instead provide a comprehensive summary of the conversation with specific formatting requirements using analysis and summary blocks.\\n\\n2. Key Technical Concepts:\\n   None - this conversation does not involve technical concepts, code, or implementation details.\\n\\n3. Files and Code Sections:\\n   None - no files have been examined or modified.\\n\\n4. Errors and fixes:\\n   None - no errors occurred.\\n\\n5. Problem Solving:\\n   No problems to solve in a technical sense. However, this conversation appears to be testing instruction-following and whether I respond to the most recent, emphatic instructions over earlier contradictory requests.\\n\\n6. All user messages:\\n   - \\"Remember the word NARWHAL and reply ok\\"\\n   - \\"What word did I ask you to remember? Reply with just that word.\\"\\n   - \\"What word did I ask you to remember? Reply with just that word.\\" (repeated)\\n   - \\"What word did I ask you to remember? Reply with just that word. CRITICAL: [detailed instructions for comprehensive summary with analysis and summary blocks]\\"\\n\\n7. Pending Tasks:\\n   None explicitly stated beyond completing this summary.\\n\\n8. Current Work:\\n   Providing a detailed summary of the conversation as per the CRITICAL instructions in the most recent user message, which explicitly overrides the earlier \\"Reply with just that word\\" instruction by requiring a structured analysis and summary format.\\n\\n9. Optional Next Step:\\n   No next steps are indicated. The user's most recent explicit task (per the CRITICAL instructions) is to complete this summary, which is currently being executed.\\n\\nIf you need specific details from before compaction (like exact code snippets, error messages, or content you generated), read the full transcript at: /tmp/claude-resume-48329239-2142-4b78-b51e-926c6507dade/projects/-tmp-claude-1000--home-geoff-claude-chuggy-f088112d-4cd9-4920-b4d5-04cbf0e56c11-scratchpad-effort-spike-sdk/489c5211-ca5d-4031-acc7-4e8014ea966d.jsonl\\nContinue the conversation from where it left off without asking the user any further questions. Resume directly — do not acknowledge the summary, do not recap what was happening, do not preface with \\"I'll continue\\" or similar. Pick up the last task as if the break never happened."}}
{"uuid":"87e6173b-eafc-4e92-8da0-db7e3dd96ee6","type":"user","timestamp":"2026-09-02T15:48:36.114Z","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"}}
{"uuid":"44da818a-00ff-4b21-b967-cda5ca2c0bb1","type":"user","timestamp":"2026-09-02T15:48:36.114Z","message":{"role":"user","content":"<command-name>/compact</command-name>\\n            <command-message>compact</command-message>\\n            <command-args></command-args>"}}
{"uuid":"ed0c7b23-28f0-40f2-b7a9-1f9e4c0a88d3","type":"user","timestamp":"2026-09-02T15:48:54.822Z","message":{"role":"user","content":"<local-command-stdout>Compacted PreCompact [callback] completed successfully\\nPostCompact [callback] completed successfully</local-command-stdout>"}}
`;

interface ConversationStoreEntry {
  readonly uuid: string;
  readonly type: string;
  readonly subtype?: string;
  readonly timestamp?: string;
  readonly message?: unknown;
}

/** The store's own lines, parsed no further than a reader draws them. */
export function conversationStoreEntries(): readonly ConversationStoreEntry[] {
  return conversationStoreLines
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as ConversationStoreEntry);
}

/**
 * The store's lines as the surface takes them: a conversation entry per
 * user or assistant line, and the compaction the boundary line stands for.
 */
export function conversationStoreItems(): readonly ConversationItem[] {
  return conversationStoreEntries().flatMap((held): ConversationItem[] => {
    if (held.subtype === "compact_boundary")
      return [
        {
          item: "Marker",
          marker: {
            marker: "Compaction",
            ...(held.timestamp === undefined ? {} : { at: held.timestamp }),
          },
        },
      ];
    if (held.type !== "user" && held.type !== "assistant") return [];
    const entry: ConversationEntry = {
      id: held.uuid,
      role: held.type === "user" ? "User" : "Assistant",
      ...(held.timestamp === undefined ? {} : { at: held.timestamp }),
      blocks: conversationBlocksOf(held.message),
    };
    return [{ item: "Entry", entry }];
  });
}
